// SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcat.ca>
// SPDX-License-Identifier: MIT

package toolconfigs

import (
	"strconv"
	"strings"
)

func renderBanditConfig(config configMap) (string, error) {
	payload := orderedMap{
		{
			Key: "exclude_dirs",
			Value: configuredList(
				config,
				"tooling.bandit.exclude_dirs",
				[]string{"tests", ".venv", "build", "dist", "node_modules"},
			),
		},
		{
			Key:   "skips",
			Value: stringList(getPath(config, "tooling.bandit.skips", []any{})),
		},
	}

	return spdxHeader + renderToolConfigProvenance(
		config,
		"bandit",
	) + renderYAML(
		payload,
	), nil
}

func renderSQLFluffConfig(config configMap) (string, error) {
	values := map[string]string{
		"dialect":   configuredString(config, "tooling.sqlfluff.dialect", "ansi"),
		"templater": configuredString(config, "tooling.sqlfluff.templater", "raw"),
		"max_line_length": strconv.Itoa(
			configuredInt(
				config,
				"tooling.sqlfluff.max_line_length",
				lineLength(config),
			),
		),
	}
	if rules := stringList(
		getPath(config, "tooling.sqlfluff.exclude_rules", []any{}),
	); len(
		rules,
	) > 0 {
		values["exclude_rules"] = strings.Join(rules, ",")
	}

	if rules := stringList(
		getPath(config, "tooling.sqlfluff.rules", []any{}),
	); len(
		rules,
	) > 0 {
		values["rules"] = strings.Join(rules, ",")
	}

	var builder strings.Builder
	builder.WriteString(spdxHeader)
	writeINISection(&builder, "sqlfluff", values, []string{
		"dialect", "templater", "max_line_length", "exclude_rules", "rules",
	})

	return finishINI(&builder), nil
}

func renderTombiConfig(config configMap) (string, error) {
	_ = config

	return strings.Join([]string{
		"# " + spdxCopyright,
		"# SPDX-License-Identifier: MIT",
		"",
		"# Generated by coding-ethos. Tombi currently discovers this file as",
		"# project configuration; keep it intentionally minimal until stricter",
		"# schema-backed TOML policy is introduced.",
		"",
	}, "\n"), nil
}

func renderGolangCIConfig(config configMap) (string, error) {
	payload := cloneMap(mappingValue(config, "tooling.golangci_lint"))
	if len(payload) == 0 {
		payload = configMap{}
	}

	payload["version"] = truthyString(valueOr(payload["version"], "2"))
	linters := cloneMap(mapValue(payload["linters"]))
	settings := cloneMap(mapValue(linters["settings"]))
	lll := cloneMap(mapValue(settings["lll"]))
	lll["line-length"] = lineLength(config)
	settings["lll"] = lll
	linters["settings"] = settings
	payload["linters"] = linters

	return spdxHeader + renderToolConfigProvenance(
		config,
		"golangci_lint",
	) + renderYAML(
		payload,
	), nil
}
