#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcat.ca>
# SPDX-License-Identifier: MIT

set -euo pipefail

usage() {
  cat >&2 << 'USAGE'
Usage:
  install-managed-toolchain.sh <manifest-source> <go-bin-dir> <github-bin-dir> <installed-manifest>

Installs every required third-party hook tool into checkout-local managed
directories. The source manifest is tab-separated and records pinned versions
and SHA-256 digests for GitHub release assets.
USAGE
  exit 2
}

[[ "$#" -eq 4 ]] || usage

SOURCE_MANIFEST="$1"
GO_BIN_DIR="$(mkdir -p "$2" && cd "$2" && pwd)"
GITHUB_BIN_DIR="$(mkdir -p "$3" && cd "$3" && pwd)"
INSTALLED_MANIFEST="$4"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

require_file() {
  [[ -f "$1" ]] || {
    printf 'FATAL: managed toolchain manifest not found: %s\n' "$1" >&2
    exit 1
  }
}

managed_dest_dir() {
  case "${1:?destination required}" in
    go-bin)
      printf '%s\n' "$GO_BIN_DIR"
      ;;
    github-bin)
      printf '%s\n' "$GITHUB_BIN_DIR"
      ;;
    *)
      printf 'FATAL: unknown managed tool destination: %s\n' "$1" >&2
      exit 2
      ;;
  esac
}

install_go_tool() {
  local tool="${1:?tool required}"
  local source="${2:?module required}"
  local version="${3:?version required}"
  local binary="${4:?binary required}"
  local sha256="${5:?sha256 required}"
  local dest_dir="${6:?dest dir required}"

  if managed_tool_already_installed "$tool" go "$source" "$version" "-" "$binary" "$sha256" "$dest_dir"; then
    return
  fi
  GOBIN="$dest_dir" "${SCRIPT_DIR}/install-source-tool.sh" \
    go "${source}@${version}"
}

install_github_tool() {
  local tool="${1:?tool required}"
  local source="${2:?repo required}"
  local version="${3:?version required}"
  local asset_substring="${4:?asset substring required}"
  local binary="${5:?binary required}"
  local sha256="${6:?sha256 required}"
  local dest_dir="${7:?dest dir required}"

  if managed_tool_already_installed \
    "$tool" github "$source" "$version" "$asset_substring" "$binary" "$sha256" "$dest_dir"; then
    return
  fi
  "${SCRIPT_DIR}/install-github-binary.sh" \
    "$source" "$version" "$asset_substring" "$binary" "$dest_dir" "$sha256"
}

managed_tool_already_installed() {
  local tool="${1:?tool required}"
  local installer="${2:?installer required}"
  local source="${3:?source required}"
  local version="${4:?version required}"
  local asset_substring="${5:?asset substring required}"
  local binary="${6:?binary required}"
  local sha256="${7:?sha256 required}"
  local dest_dir="${8:?dest dir required}"
  local installed_path="${dest_dir}/${binary}"

  [[ -x "$installed_path" && -f "$INSTALLED_MANIFEST" ]] || return 1
  grep -Fqx \
    "${tool}	${installer}	${source}	${version}	${asset_substring}	${binary}	${sha256}	${installed_path}" \
    "$INSTALLED_MANIFEST"
}

require_file "$SOURCE_MANIFEST"
mkdir -p "$GO_BIN_DIR" "$GITHUB_BIN_DIR" "$(dirname "$INSTALLED_MANIFEST")"

tmp_manifest="${INSTALLED_MANIFEST}.tmp.$$"
{
  printf '# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcat.ca>\n'
  printf '# SPDX-License-Identifier: MIT\n'
  printf '# Generated by install-managed-toolchain.sh. Do not edit.\n'
  printf '# tool\tinstaller\tsource\tversion\tasset_substring\tbinary\tsha256\tpath\n'
} > "$tmp_manifest"

while IFS=$'\t' read -r tool installer source version asset_substring binary sha256 dest; do
  [[ -n "${tool:-}" ]] || continue
  [[ "$tool" != \#* ]] || continue

  dest_dir="$(managed_dest_dir "$dest")"
  case "$installer" in
    go)
      install_go_tool "$tool" "$source" "$version" "$binary" "$sha256" "$dest_dir"
      ;;
    github)
      install_github_tool "$tool" "$source" "$version" "$asset_substring" "$binary" "$sha256" "$dest_dir"
      ;;
    *)
      printf 'FATAL: unknown installer %q for managed tool %q\n' "$installer" "$tool" >&2
      rm -f "$tmp_manifest"
      exit 2
      ;;
  esac

  installed_path="${dest_dir}/${binary}"
  if [[ ! -x "$installed_path" ]]; then
    printf 'FATAL: managed tool %s was not installed as executable: %s\n' \
      "$tool" "$installed_path" >&2
    rm -f "$tmp_manifest"
    exit 1
  fi
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$tool" "$installer" "$source" "$version" "$asset_substring" \
    "$binary" "$sha256" "$installed_path" >> "$tmp_manifest"
done < "$SOURCE_MANIFEST"

mv -f "$tmp_manifest" "$INSTALLED_MANIFEST"
