from typing import Final

SHELL_REVIEW_PROMPT_TEMPLATE: Final[str]
SHELL_ETHOS_PROMPT_TEMPLATE: Final[str]
SHELL_DOCUMENTATION_PROMPT_TEMPLATE: Final[str]
SHELLCHECK_SUPPRESSION_PROMPT_TEMPLATE: Final[str]
SHELL_PLACEHOLDER_PROMPT_TEMPLATE: Final[str]
SHELL_ETHOS_QUICK_REFERENCE: Final[str]
