// SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcat.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//nolint:tagliatelle // Provider hook schemas use mixed native JSON naming.
package agenthooks

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"time"

	"go.yaml.in/yaml/v3"

	"blackcat.ca/coding-ethos/go/internal/apperror"
	"blackcat.ca/coding-ethos/go/internal/execguard"
	"blackcat.ca/coding-ethos/go/internal/memories"
	"blackcat.ca/coding-ethos/go/internal/safeexec"
	"blackcat.ca/coding-ethos/go/internal/shellparse"
	"blackcat.ca/coding-ethos/go/internal/toolaliases"
)

const (
	codexConfigGrowth = 2
	mcpServerName     = "coding-ethos"
	probeTimeout      = 30 * time.Second
	settingsDirMode   = 0o755
	settingsFileMode  = 0o600

	eventPreToolUse        = "PreToolUse"
	eventPostToolUse       = "PostToolUse"
	eventPermissionRequest = "PermissionRequest"
	eventSessionStart      = "SessionStart"
	eventUserPromptSubmit  = "UserPromptSubmit"
	eventStop              = "Stop"
	eventBeforeTool        = "BeforeTool"
	eventAfterTool         = "AfterTool"

	verifyStatusFail    = "fail"
	verifyStatusInvalid = "invalid"
	verifyStatusPass    = "pass"
	verifyStatusValid   = "valid"
)

const managedGeneratedComment = "# Generated by coding-ethos. Edit " +
	"coding_ethos.yml/config.yaml inputs, not this block.\n"

var (
	errHookCommandRequired     = apperror.StaticError("hook command is required")
	errMissingSkillFrontmatter = apperror.StaticError(
		"generated skill is missing YAML frontmatter",
	)
	errSettingsMismatch = apperror.StaticError(
		"agent hook settings do not contain expected hooks for all providers",
	)
	errUnsupportedHookCommand = apperror.StaticError(
		"unsupported hook command for direct probe",
	)
	errCodexTrustMismatch = apperror.StaticError(
		"Codex user config does not trust generated project hooks",
	)
)

type commandHook struct {
	Name          string `json:"name,omitempty"`
	Type          string `json:"type"`
	Command       string `json:"command"`
	StatusMessage string `json:"statusMessage,omitempty"`
	Timeout       int    `json:"timeout,omitempty"`
}

type matcherHook struct {
	Matcher string        `json:"matcher,omitempty"`
	Hooks   []commandHook `json:"hooks"`
}

type claudeSettings struct {
	Hooks       map[string][]matcherHook `json:"hooks"`
	HooksConfig map[string]any           `json:"hooksConfig,omitempty"`
}

type ProviderCapability struct {
	Provider            string   `json:"provider"`
	DisplayName         string   `json:"display_name"`
	Coverage            string   `json:"coverage"`
	NativeFiles         []string `json:"native_files"`
	HookEvents          []string `json:"hook_events"`
	BlockResponseShape  string   `json:"block_response_shape"`
	ContextAdviceShape  string   `json:"context_advice_shape"`
	MCPSetup            string   `json:"mcp_setup"`
	SettingsTarget      string   `json:"settings_target"`
	GeneratedTargets    []string `json:"generated_targets"`
	MemoryInterception  string   `json:"memory_interception"`
	MemoryFallback      string   `json:"memory_fallback"`
	Supported           []string `json:"supported"`
	ProviderLimited     []string `json:"provider_limited,omitempty"`
	Unsupported         []string `json:"unsupported,omitempty"`
	VerificationFixture string   `json:"verification_fixture"`
	SafetyCaveats       []string `json:"safety_caveats,omitempty"`
}

type allSettings struct {
	Claude       claudeSettings       `json:"claude"`
	Codex        claudeSettings       `json:"codex"`
	Gemini       claudeSettings       `json:"gemini"`
	Capabilities []ProviderCapability `json:"capabilities"`
}

type mcpServer struct {
	Command string   `json:"command"`
	Args    []string `json:"args"`
}

func (server mcpServer) claudeJSON() map[string]any {
	payload := map[string]any{
		"type":    "stdio",
		"command": server.Command,
		"args":    append([]string(nil), server.Args...),
	}

	return payload
}

func (server mcpServer) geminiJSON() map[string]any {
	payload := map[string]any{
		"command": server.Command,
		"args":    append([]string(nil), server.Args...),
	}

	return payload
}

func mcpServerConfig(hookCommand string) (mcpServer, error) {
	command, found := strings.CutSuffix(strings.TrimSpace(hookCommand), " agent-hook")
	if !found || strings.TrimSpace(command) == "" {
		return mcpServer{}, fmt.Errorf(
			"derive MCP command from hook command %q: %w",
			hookCommand,
			errHookCommandRequired,
		)
	}

	return mcpServer{
		Command: command,
		Args:    []string{"mcp"},
	}, nil
}

type SettingsPaths struct {
	Claude      string
	ClaudeMCP   string
	CodexConfig string
	CodexHooks  string
	Gemini      string
}

// VerifyReport describes the installed native hook surfaces and runnable smoke
// checks performed by agent-hooks verify.
type VerifyReport struct {
	Status       string               `json:"status"`
	Checks       []VerifyCheck        `json:"checks"`
	Capabilities []ProviderCapability `json:"capabilities"`
}

// VerifyCheck records one provider-native hook payload probe.
type VerifyCheck struct {
	Provider string `json:"provider"`
	Event    string `json:"event"`
	Tool     string `json:"tool"`
	Status   string `json:"status"`
	Detail   string `json:"detail,omitempty"`
}

type hookProbe struct {
	validate func(hookProbeResult) error
	provider string
	event    string
	tool     string
	payload  string
}

type hookProbeResult struct {
	payload  map[string]any
	stdout   string
	stderr   string
	exitCode int
}

// HookProbeSummary exposes the provider and payload covered by a doctor probe.
type HookProbeSummary struct {
	Provider string
	Payload  string
}

func DefaultSettingsPaths(root string) SettingsPaths {
	if root == "" {
		root = "."
	}

	return SettingsPaths{
		Claude:      filepath.Join(root, ".claude", "settings.local.json"),
		ClaudeMCP:   filepath.Join(root, ".mcp.json"),
		CodexConfig: filepath.Join(root, ".codex", "config.toml"),
		CodexHooks:  filepath.Join(root, ".codex", "hooks.json"),
		Gemini:      filepath.Join(root, ".gemini", "settings.json"),
	}
}

func WriteSettings(writer io.Writer, hookCommand string) error {
	settings, err := buildAllSettings(hookCommand)
	if err != nil {
		return err
	}

	encoder := json.NewEncoder(writer)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")

	err = encoder.Encode(settings)
	if err != nil {
		return fmt.Errorf("encode settings: %w", err)
	}

	return nil
}

func SyncSettings(root, hookCommand string) error {
	settings, err := buildAllSettings(hookCommand)
	if err != nil {
		return err
	}

	serverConfig, err := mcpServerConfig(hookCommand)
	if err != nil {
		return err
	}

	paths := DefaultSettingsPaths(root)

	err = syncSettingsFile(paths.Claude, func(payload map[string]any) {
		payload["hooks"] = settings.Claude.Hooks
	})
	if err != nil {
		return err
	}

	err = syncClaudeMCPConfig(paths.ClaudeMCP, serverConfig)
	if err != nil {
		return err
	}

	err = syncCodexConfig(paths.CodexConfig, settings.Codex, serverConfig)
	if err != nil {
		return err
	}

	err = removeStaleCodexHooksFile(paths.CodexHooks)
	if err != nil {
		return err
	}

	_, err = memories.ImportExisting(root)
	if err != nil {
		return fmt.Errorf("import existing memories: %w", err)
	}

	err = syncSettingsFile(paths.Gemini, func(payload map[string]any) {
		payload["hooksConfig"] = settings.Gemini.HooksConfig
		payload["hooks"] = settings.Gemini.Hooks
		syncMCPServers(payload, serverConfig.geminiJSON())
	})
	if err != nil {
		return err
	}

	return nil
}

func syncClaudeMCPConfig(path string, server mcpServer) error {
	return syncSettingsFile(path, func(payload map[string]any) {
		syncMCPServers(payload, server.claudeJSON())
	})
}

func syncMCPServers(payload, server map[string]any) {
	servers := mapFromAny(payload["mcpServers"])
	servers[mcpServerName] = server
	payload["mcpServers"] = servers
}

func mapFromAny(value any) map[string]any {
	existing, found := value.(map[string]any)
	if !found {
		return map[string]any{}
	}

	copied := make(map[string]any, len(existing))
	maps.Copy(copied, existing)

	return copied
}

func syncCodexConfig(path string, settings claudeSettings, server mcpServer) error {
	return syncTextSettingsFile(path, func(content string) string {
		return ensureCodexConfig(content, settings, server)
	})
}

func removeStaleCodexHooksFile(path string) error {
	err := os.Remove(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("remove stale Codex hooks file %s: %w", path, err)
	}

	return nil
}

func syncSettingsFile(path string, merge func(map[string]any)) error {
	content, err := renderSettingsFileContent(path, merge)
	if err != nil {
		return err
	}

	return writeSettingsFile(path, content)
}

func renderSettingsFileContent(
	path string,
	merge func(map[string]any),
) (string, error) {
	payload, err := existingSettingsPayload(path)
	if err != nil {
		return "", err
	}

	merge(payload)

	var buffer bytes.Buffer

	encoder := json.NewEncoder(&buffer)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")

	err = encoder.Encode(payload)
	if err != nil {
		return "", fmt.Errorf("encode settings: %w", err)
	}

	return buffer.String(), nil
}

func syncTextSettingsFile(path string, mutate func(string) string) error {
	content, err := renderTextSettingsFileContent(path, mutate)
	if err != nil {
		return err
	}

	return writeSettingsFile(path, content)
}

func writeSettingsFile(path, content string) error {
	err := os.MkdirAll(filepath.Dir(path), settingsDirMode)
	if err != nil {
		return fmt.Errorf("create settings directory: %w", err)
	}

	err = os.WriteFile(path, []byte(content), settingsFileMode)
	if err != nil {
		return fmt.Errorf("write settings: %w", err)
	}

	return nil
}

func renderTextSettingsFileContent(
	path string,
	mutate func(string) string,
) (string, error) {
	content := ""

	data, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return "", fmt.Errorf("read settings: %w", err)
	}

	if err == nil {
		content = string(data)
	}

	return mutate(content), nil
}

func ensureCodexHookFeature(content string) string {
	lines := strings.Split(content, "\n")
	rewrite := codexConfigRewrite{
		output: make([]string, 0, len(lines)+codexConfigGrowth),
	}

	for _, line := range lines {
		rewrite.accept(line)
	}

	rewrite.finish()

	return strings.TrimRight(strings.Join(rewrite.output, "\n"), "\n") + "\n"
}

func ensureCodexConfig(
	content string,
	settings claudeSettings,
	server mcpServer,
) string {
	withoutManaged := removeCodexManagedConfig(content)
	withFeature := ensureCodexHookFeature(withoutManaged)

	return strings.TrimRight(withFeature, "\n") + "\n\n" +
		renderManagedCodexHooksBlock(settings) + "\n" +
		renderManagedCodexMCPBlock(server)
}

func removeCodexManagedConfig(content string) string {
	return removeCodexMCPSection(
		removeCodexHooksSection(removeManagedCodexBlocks(content)),
	)
}

func removeManagedCodexBlocks(content string) string {
	lines := strings.Split(content, "\n")
	output := make([]string, 0, len(lines))
	inManagedBlock := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "# BEGIN coding-ethos managed "):
			inManagedBlock = true

			continue
		case strings.HasPrefix(trimmed, "# END coding-ethos managed ") && inManagedBlock:
			inManagedBlock = false

			continue
		case inManagedBlock:
			continue
		default:
			output = append(output, line)
		}
	}

	return strings.TrimRight(strings.Join(output, "\n"), "\n") + "\n"
}

func removeCodexMCPSection(content string) string {
	lines := strings.Split(content, "\n")
	output := make([]string, 0, len(lines))
	inMCP := false
	inMCPEnv := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case trimmed == "[mcp_servers."+mcpServerName+"]":
			inMCP = true
			inMCPEnv = false

			continue
		case trimmed == "[mcp_servers."+mcpServerName+".env]":
			inMCP = false
			inMCPEnv = true

			continue
		case (inMCP || inMCPEnv) && strings.HasPrefix(trimmed, "[") &&
			strings.HasSuffix(trimmed, "]"):
			inMCP = false
			inMCPEnv = false
		case inMCP || inMCPEnv:
			continue
		}

		output = append(output, line)
	}

	return strings.TrimRight(strings.Join(output, "\n"), "\n") + "\n"
}

func removeCodexHooksSection(content string) string {
	lines := strings.Split(content, "\n")
	output := make([]string, 0, len(lines))
	inHooks := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case trimmed == "[hooks]":
			inHooks = true

			continue
		case inHooks && strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]"):
			inHooks = false
		case inHooks:
			continue
		case strings.HasPrefix(trimmed, "hooks."):
			continue
		}

		output = append(output, line)
	}

	return strings.TrimRight(strings.Join(output, "\n"), "\n") + "\n"
}

func renderManagedCodexHooksBlock(settings claudeSettings) string {
	var builder strings.Builder
	builder.WriteString("# BEGIN coding-ethos managed hooks\n")
	builder.WriteString(managedGeneratedComment)
	builder.WriteString("[hooks]\n")

	for _, event := range codexHookEventOrder() {
		matchers := settings.Hooks[event]
		if len(matchers) == 0 {
			continue
		}

		builder.WriteString(codexHookEventKey(event))
		builder.WriteString(" = [\n")

		for _, matcher := range matchers {
			builder.WriteString("  { ")

			if matcher.Matcher != "" {
				builder.WriteString("matcher = ")
				builder.WriteString(tomlString(matcher.Matcher))
				builder.WriteString(", ")
			}

			builder.WriteString("hooks = [{ type = \"command\", command = ")
			builder.WriteString(tomlString(matcher.Hooks[0].Command))

			if matcher.Hooks[0].StatusMessage != "" {
				builder.WriteString(", statusMessage = ")
				builder.WriteString(tomlString(matcher.Hooks[0].StatusMessage))
			}

			builder.WriteString(", timeout = 30 }]")
			builder.WriteString(" },\n")
		}

		builder.WriteString("]\n")
	}

	builder.WriteString("# END coding-ethos managed hooks\n")

	return builder.String()
}

func renderManagedCodexMCPBlock(server mcpServer) string {
	var builder strings.Builder
	builder.WriteString("# BEGIN coding-ethos managed mcp\n")
	builder.WriteString(managedGeneratedComment)
	builder.WriteString("[mcp_servers.")
	builder.WriteString(mcpServerName)
	builder.WriteString("]\n")
	builder.WriteString("command = ")
	builder.WriteString(tomlString(server.Command))
	builder.WriteString("\n")
	builder.WriteString("args = [")

	for index, arg := range server.Args {
		if index > 0 {
			builder.WriteString(", ")
		}

		builder.WriteString(tomlString(arg))
	}

	builder.WriteString("]\n")
	builder.WriteString("# END coding-ethos managed mcp\n")

	return builder.String()
}

func codexHookEventOrder() []string {
	return []string{
		eventPreToolUse,
		eventPermissionRequest,
		eventPostToolUse,
		eventSessionStart,
		eventUserPromptSubmit,
		eventStop,
	}
}

func codexHookEventKey(event string) string {
	return event
}

func tomlString(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return `""`
	}

	return string(encoded)
}

type codexConfigRewrite struct {
	output      []string
	inFeatures  bool
	sawFeatures bool
	wroteFlag   bool
}

func (rewrite *codexConfigRewrite) accept(line string) {
	if enteringNewSection(line) {
		rewrite.closeFeaturesSection()
		rewrite.inFeatures = strings.TrimSpace(line) == "[features]"
		rewrite.sawFeatures = rewrite.sawFeatures || rewrite.inFeatures
	}

	if rewrite.inFeatures && isCodexHookFlag(line) {
		rewrite.output = append(rewrite.output, codexHookFeatureLine())
		rewrite.wroteFlag = true

		return
	}

	if line != "" || len(rewrite.output) > 0 {
		rewrite.output = append(rewrite.output, line)
	}
}

func (rewrite *codexConfigRewrite) finish() {
	if rewrite.sawFeatures && !rewrite.wroteFlag {
		rewrite.output = append(rewrite.output, codexHookFeatureLine())
	}

	if !rewrite.sawFeatures {
		rewrite.appendFeaturesSection()
	}
}

func (rewrite *codexConfigRewrite) closeFeaturesSection() {
	if rewrite.inFeatures && !rewrite.wroteFlag {
		rewrite.output = append(rewrite.output, codexHookFeatureLine())
		rewrite.wroteFlag = true
	}
}

func (rewrite *codexConfigRewrite) appendFeaturesSection() {
	if len(rewrite.output) > 0 && rewrite.output[len(rewrite.output)-1] != "" {
		rewrite.output = append(rewrite.output, "")
	}

	rewrite.output = append(rewrite.output, "[features]", codexHookFeatureLine())
}

func enteringNewSection(line string) bool {
	trimmed := strings.TrimSpace(line)

	return strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]")
}

func isCodexHookFlag(line string) bool {
	trimmed := strings.TrimSpace(line)
	key, _, _ := strings.Cut(trimmed, "=")

	return strings.TrimSpace(key) == "hooks" || strings.TrimSpace(key) == "codex_hooks"
}

func codexHookFeatureLine() string {
	return "hooks = true"
}

func existingSettingsPayload(path string) (map[string]any, error) {
	file, err := os.Open(path)
	if errors.Is(err, os.ErrNotExist) {
		return map[string]any{}, nil
	}

	if err != nil {
		return nil, fmt.Errorf("open existing settings: %w", err)
	}

	defer file.Close()

	payload := map[string]any{}

	err = json.NewDecoder(file).Decode(&payload)
	if err != nil {
		return nil, fmt.Errorf("decode existing settings: %w", err)
	}

	return payload, nil
}

func DoctorSettings(root, hookCommand string) error {
	expected, err := buildAllSettings(hookCommand)
	if err != nil {
		return err
	}

	expectedMCP, err := mcpServerConfig(hookCommand)
	if err != nil {
		return err
	}

	paths := DefaultSettingsPaths(root)
	checks := []struct {
		found func(map[string]any) bool
		path  string
	}{
		{path: paths.Claude, found: func(payload map[string]any) bool {
			return claudePayloadContainsExpectedHooks(payload, expected.Claude)
		}},
		{path: paths.Gemini, found: func(payload map[string]any) bool {
			return nativePayloadContainsExpectedHooks(payload, expected.Gemini) &&
				payloadContainsExpectedMCPServer(payload, expectedMCP.geminiJSON())
		}},
		{path: paths.ClaudeMCP, found: func(payload map[string]any) bool {
			return payloadContainsExpectedMCPServer(payload, expectedMCP.claudeJSON())
		}},
	}

	for _, check := range checks {
		payload, readErr := existingSettingsPayload(check.path)
		if readErr != nil {
			return readErr
		}

		if !check.found(payload) {
			return errSettingsMismatch
		}
	}

	config, readErr := os.ReadFile(paths.CodexConfig)
	if readErr != nil {
		return fmt.Errorf("read Codex config: %w", readErr)
	}

	if !codexHookFeatureEnabled(string(config)) {
		return errSettingsMismatch
	}

	if !codexConfigContainsExpectedHooks(string(config), expected.Codex) {
		return errSettingsMismatch
	}

	if !codexConfigContainsExpectedMCPServer(string(config), expectedMCP) {
		return errSettingsMismatch
	}

	err = memories.Verify(root)
	if err != nil {
		return fmt.Errorf("verify memory surfaces: %w", err)
	}

	return nil
}

func payloadContainsExpectedMCPServer(
	payload map[string]any,
	expected map[string]any,
) bool {
	servers := mapFromAny(payload["mcpServers"])
	server := mapFromAny(servers[mcpServerName])

	for key, expectedValue := range expected {
		switch typedExpected := expectedValue.(type) {
		case []string:
			if !stringSliceFromAnyMatches(server[key], typedExpected) {
				return false
			}
		default:
			if server[key] != typedExpected {
				return false
			}
		}
	}

	return true
}

func stringSliceFromAnyMatches(value any, expected []string) bool {
	values, found := value.([]any)
	if !found {
		if typed, typedOK := value.([]string); typedOK {
			return slices.Equal(typed, expected)
		}

		return false
	}

	if len(values) != len(expected) {
		return false
	}

	for index, value := range values {
		if value != expected[index] {
			return false
		}
	}

	return true
}

func codexConfigContainsExpectedHooks(
	content string,
	expected claudeSettings,
) bool {
	for event, expectedMatchers := range expected.Hooks {
		eventKey := codexHookEventKey(event)
		if !strings.Contains(content, eventKey+" = [") {
			return false
		}

		for _, expectedMatcher := range expectedMatchers {
			if !strings.Contains(
				content,
				"command = "+tomlString(expectedMatcher.Hooks[0].Command),
			) {
				return false
			}

			if expectedMatcher.Matcher != "" &&
				!strings.Contains(
					content,
					"matcher = "+tomlString(expectedMatcher.Matcher),
				) {
				return false
			}
		}
	}

	return true
}

func codexConfigContainsExpectedMCPServer(content string, expected mcpServer) bool {
	return strings.Contains(content, "[mcp_servers."+mcpServerName+"]") &&
		strings.Contains(content, "command = "+tomlString(expected.Command)) &&
		strings.Contains(content, "args = ["+tomlString(expected.Args[0])+"]")
}

func VerifySettings(root, hookCommand string) (VerifyReport, error) {
	err := DoctorSettings(root, hookCommand)
	if err != nil {
		return VerifyReport{
			Status:       verifyStatusInvalid,
			Capabilities: ProviderCapabilities(),
			Checks: []VerifyCheck{{
				Provider: "all",
				Event:    "settings",
				Status:   verifyStatusFail,
				Detail:   err.Error(),
			}},
		}, err
	}

	report := VerifyReport{
		Status:       verifyStatusValid,
		Capabilities: ProviderCapabilities(),
	}

	err = appendSkillSurfaceChecks(root, &report)
	if err != nil {
		return report, err
	}

	for _, probe := range hookProbes() {
		result, err := runHookProbe(root, hookCommand, probe)

		check := VerifyCheck{
			Provider: probe.provider,
			Event:    probe.event,
			Tool:     probe.tool,
			Status:   verifyStatusPass,
		}
		if err != nil {
			check.Status = verifyStatusFail
			check.Detail = err.Error()
			report.Status = verifyStatusInvalid
			report.Checks = append(report.Checks, check)

			return report, err
		}

		err = probe.validate(result)
		if err != nil {
			check.Status = verifyStatusFail
			check.Detail = err.Error()
			report.Status = verifyStatusInvalid
			report.Checks = append(report.Checks, check)

			return report, err
		}

		report.Checks = append(report.Checks, check)
	}

	return report, nil
}

func appendSkillSurfaceChecks(root string, report *VerifyReport) error {
	checks, err := verifySkillSurfaces(root)

	report.Checks = append(report.Checks, checks...)
	if err != nil {
		report.Status = verifyStatusInvalid

		return err
	}

	return nil
}

func verifySkillSurfaces(root string) ([]VerifyCheck, error) {
	skillIDs, err := repoSkillIDs(root)
	if err != nil {
		return nil, err
	}

	if len(skillIDs) == 0 {
		return nil, nil
	}

	checks := make([]VerifyCheck, 0, len(skillIDs)*skillSurfaceCount)

	var verifyErr error

	for _, skillID := range skillIDs {
		for _, surface := range skillSurfacePaths(root, skillID) {
			check := VerifyCheck{
				Provider: surface.provider,
				Event:    "skill-surface",
				Tool:     skillID,
				Status:   verifyStatusPass,
			}

			err := verifySkillFile(surface.path, skillID)
			if err != nil {
				check.Status = verifyStatusFail
				check.Detail = err.Error()
				verifyErr = errors.Join(verifyErr, err)
			}

			checks = append(checks, check)
		}
	}

	return checks, verifyErr
}

const skillSurfaceCount = 4

type skillSurfacePath struct {
	provider string
	path     string
}

func repoSkillIDs(root string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(root, ".agents", "skills"))
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}

	if err != nil {
		return nil, fmt.Errorf("read generated skill directory: %w", err)
	}

	skillIDs := []string{}

	for _, entry := range entries {
		if entry.IsDir() {
			skillIDs = append(skillIDs, entry.Name())
		}
	}

	slices.Sort(skillIDs)

	return skillIDs, nil
}

func skillSurfacePaths(root, skillID string) []skillSurfacePath {
	entrypoint := filepath.Join(skillID, "SKILL.md")

	return []skillSurfacePath{
		{
			provider: string(ProviderGeneric),
			path:     filepath.Join(root, ".agents", "skills", entrypoint),
		},
		{
			provider: string(ProviderClaude),
			path:     filepath.Join(root, ".claude", "skills", entrypoint),
		},
		{
			provider: string(ProviderCodex),
			path:     filepath.Join(root, ".codex", "skills", entrypoint),
		},
		{
			provider: string(ProviderGemini),
			path: filepath.Join(
				root,
				".gemini",
				"extensions",
				"coding-ethos",
				"skills",
				entrypoint,
			),
		},
	}
}

func verifySkillFile(path, skillID string) error {
	content, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		return fmt.Errorf("read generated skill %s: %w", path, err)
	}

	frontmatter, err := parseSkillFrontmatter(string(content))
	if err != nil {
		return fmt.Errorf("read generated skill metadata %s: %w", path, err)
	}

	if frontmatter.Name != skillID ||
		frontmatter.EffectiveSource() != "coding_ethos.yml" {
		return apperror.Wrapf(
			apperror.StaticError("generated skill %s does not match skill %s"),
			"generated skill %s does not match skill %s",
			path,
			skillID,
		)
	}

	return nil
}

type skillFrontmatter struct {
	Metadata struct {
		Source string `yaml:"source"`
	} `yaml:"metadata"`
	Name   string `yaml:"name"`
	Source string `yaml:"source"`
}

func (frontmatter skillFrontmatter) EffectiveSource() string {
	if frontmatter.Metadata.Source != "" {
		return frontmatter.Metadata.Source
	}

	return frontmatter.Source
}

func parseSkillFrontmatter(content string) (skillFrontmatter, error) {
	if !strings.HasPrefix(content, "---\n") {
		return skillFrontmatter{}, errMissingSkillFrontmatter
	}

	remainder := strings.TrimPrefix(content, "---\n")

	raw, _, found := strings.Cut(remainder, "\n---")
	if !found {
		return skillFrontmatter{}, errMissingSkillFrontmatter
	}

	var frontmatter skillFrontmatter

	err := yaml.Unmarshal([]byte(raw), &frontmatter)
	if err != nil {
		return skillFrontmatter{}, fmt.Errorf("parse YAML frontmatter: %w", err)
	}

	return frontmatter, nil
}

func buildAllSettings(hookCommand string) (allSettings, error) {
	if hookCommand == "" {
		return allSettings{}, errHookCommandRequired
	}

	return allSettings{
		Claude:       buildClaudeSettings(RuntimeHookSpecs(), hookCommand),
		Codex:        buildCodexSettings(RuntimeHookSpecs(), hookCommand),
		Gemini:       buildGeminiSettings(RuntimeHookSpecs(), hookCommand),
		Capabilities: ProviderCapabilities(),
	}, nil
}

func buildClaudeSettings(specs []HookSpec, hookCommand string) claudeSettings {
	hooks := make(map[string][]matcherHook)
	for _, spec := range specs {
		hooks[spec.Event] = append(
			hooks[spec.Event],
			commandMatcher(spec.Tool, hookCommand),
		)
	}

	addNoopProviderMatchers(
		hooks,
		toolaliases.ProviderClaude,
		hookCommand,
		commandMatcher,
	)

	return claudeSettings{Hooks: hooks}
}

func buildCodexSettings(specs []HookSpec, hookCommand string) claudeSettings {
	hooks := make(map[string][]matcherHook)

	for _, spec := range specs {
		for _, matcher := range codexHookMatchers(spec) {
			hooks[spec.Event] = append(
				hooks[spec.Event],
				codexMatcher(matcher, hookCommand),
			)
		}
	}

	addNoopProviderMatchers(hooks, toolaliases.ProviderCodex, hookCommand, codexMatcher)

	return claudeSettings{Hooks: hooks}
}

func codexHookMatchers(spec HookSpec) []string {
	if spec.Event == eventSessionStart || spec.Event == eventUserPromptSubmit {
		return []string{""}
	}

	if spec.Event == eventStop {
		return []string{""}
	}

	if !codexToolEvent(spec.Event) || !codexSupportsTool(spec.Tool) {
		return nil
	}

	return []string{codexMatcherFor(spec.Tool)}
}

func codexToolEvent(event string) bool {
	return event == eventPreToolUse || event == eventPostToolUse
}

func codexSupportsTool(tool string) bool {
	return tool == toolaliases.CanonicalShell || toolaliases.IsWriteLike(tool)
}

func buildGeminiSettings(specs []HookSpec, hookCommand string) claudeSettings {
	hooks := make(map[string][]matcherHook)

	for _, spec := range specs {
		event, matcher, found := geminiHookSpec(spec)
		if !found {
			continue
		}

		hooks[event] = append(
			hooks[event],
			geminiMatcher(matcher, hookCommand),
		)
	}

	addNoopProviderMatchers(
		hooks,
		toolaliases.ProviderGemini,
		hookCommand,
		geminiMatcher,
	)

	return claudeSettings{
		Hooks:       hooks,
		HooksConfig: map[string]any{"enabled": true},
	}
}

func addNoopProviderMatchers(
	hooks map[string][]matcherHook,
	provider string,
	hookCommand string,
	build func(string, string) matcherHook,
) {
	aliases := toolaliases.ProviderAliases(provider, toolaliases.CanonicalNoop)
	for _, alias := range aliases {
		preEvent, postEvent := providerToolEvents(provider)
		hooks[preEvent] = append(
			hooks[preEvent],
			build(providerMatcher(alias), hookCommand),
		)
		hooks[postEvent] = append(
			hooks[postEvent],
			build(providerMatcher(alias), hookCommand),
		)
	}
}

func providerToolEvents(provider string) (string, string) {
	if provider == toolaliases.ProviderGemini {
		return eventBeforeTool, eventAfterTool
	}

	return eventPreToolUse, eventPostToolUse
}

func codexMatcherFor(canonical string) string {
	aliases := toolaliases.ProviderAliases(toolaliases.ProviderCodex, canonical)

	parts := make([]string, 0, len(aliases))
	for _, alias := range aliases {
		parts = append(parts, providerMatcher(alias))
	}

	return strings.Join(parts, "|")
}

func providerMatcher(alias toolaliases.Alias) string {
	if alias.Regex {
		return regexp.QuoteMeta(alias.Name)
	}

	return alias.Name
}

func claudePayloadContainsExpectedHooks(
	payload map[string]any,
	expected claudeSettings,
) bool {
	raw, err := json.Marshal(payload)
	if err != nil {
		return false
	}

	var actual claudeSettings

	err = json.Unmarshal(raw, &actual)
	if err != nil {
		return false
	}

	return settingsContainExpectedHooks(actual, expected)
}

func nativePayloadContainsExpectedHooks(
	payload map[string]any,
	expected claudeSettings,
) bool {
	return claudePayloadContainsExpectedHooks(payload, expected)
}

func commandMatcher(matcher, hookCommand string) matcherHook {
	return matcherHook{
		Matcher: matcher,
		Hooks: []commandHook{{
			Type:    "command",
			Command: hookCommand,
		}},
	}
}

func codexMatcher(matcher, hookCommand string) matcherHook {
	return matcherHook{
		Matcher: matcher,
		Hooks: []commandHook{{
			Type:          "command",
			Command:       hookCommand,
			StatusMessage: "coding-ethos policy",
		}},
	}
}

func geminiMatcher(matcher, hookCommand string) matcherHook {
	return matcherHook{
		Matcher: matcher,
		Hooks: []commandHook{{
			Name:    "coding-ethos",
			Type:    "command",
			Command: hookCommand,
		}},
	}
}

func geminiHookSpec(spec HookSpec) (string, string, bool) {
	if spec.Event == eventSessionStart {
		return eventSessionStart, "startup", true
	}

	if spec.Event == eventUserPromptSubmit {
		return "BeforeAgent", "prompt", true
	}

	if spec.Event == eventStop {
		return "AfterAgent", "stop", true
	}

	if spec.Event == "SessionEnd" {
		return "SessionEnd", "session", true
	}

	event, found := geminiToolEvent(spec.Event)
	if !found || !geminiSupportsTool(spec.Tool) {
		return "", "", false
	}

	return event, firstGeminiAlias(spec.Tool), true
}

func geminiToolEvent(event string) (string, bool) {
	switch event {
	case eventPreToolUse:
		return eventBeforeTool, true
	case eventPostToolUse:
		return eventAfterTool, true
	default:
		return "", false
	}
}

func geminiSupportsTool(tool string) bool {
	return tool == toolaliases.CanonicalShell || toolaliases.IsWriteLike(tool)
}

func firstGeminiAlias(canonical string) string {
	aliases := toolaliases.ProviderAliases(toolaliases.ProviderGemini, canonical)
	if len(aliases) == 0 {
		return canonical
	}

	return aliases[0].Name
}

func codexHookFeatureEnabled(content string) bool {
	inFeatures := false

	for line := range strings.SplitSeq(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			inFeatures = trimmed == "[features]"

			continue
		}

		if inFeatures && isCodexHookFlag(trimmed) {
			return strings.Contains(trimmed, "true")
		}
	}

	return false
}

func settingsContainExpectedHooks(
	actual claudeSettings,
	expected claudeSettings,
) bool {
	for event, expectedMatchers := range expected.Hooks {
		actualMatchers := actual.Hooks[event]
		for _, expectedMatcher := range expectedMatchers {
			if !containsMatcher(actualMatchers, expectedMatcher) {
				return false
			}
		}
	}

	return true
}

func containsMatcher(actual []matcherHook, expected matcherHook) bool {
	for _, candidate := range actual {
		if candidate.Matcher != expected.Matcher {
			continue
		}

		if containsCommandHook(candidate.Hooks, expected.Hooks[0]) {
			return true
		}
	}

	return false
}

func containsCommandHook(actual []commandHook, expected commandHook) bool {
	return slices.Contains(actual, expected)
}

func hookProbes() []hookProbe {
	probes := make([]hookProbe, 0, hookProbeCapacity)
	probes = append(probes, claudeHookProbes()...)
	probes = append(probes, codexHookProbes()...)
	probes = append(probes, geminiHookProbes()...)

	return probes
}

// HookProbeSummaries returns provider/payload metadata for doctor probes.
func HookProbeSummaries() []HookProbeSummary {
	probes := hookProbes()

	summaries := make([]HookProbeSummary, 0, len(probes))
	for _, probe := range probes {
		summaries = append(summaries, HookProbeSummary{
			Provider: probe.provider,
			Payload:  probe.payload,
		})
	}

	return summaries
}

const hookProbeCapacity = 11

const (
	hookTamperProbeCommand = "rm /repo/.git/coding-ethos-hooks/coding-ethos-git-hook" +
		" && go build -o /repo/.git/coding-ethos-hooks/coding-ethos-git-hook ."
	pythonSubprocessGitProbeCommand = "python3 -c " +
		`"import subprocess; subprocess.run(['/usr/bin/git','status'])"`
)

func claudeHookProbes() []hookProbe {
	return []hookProbe{
		{
			provider: string(ProviderClaude),
			event:    eventPreToolUse,
			tool:     toolaliases.CanonicalShell,
			payload: `{
				"provider": "claude",
				"hook_event_name": "PreToolUse",
				"tool_name": "Bash",
				"tool_input": {"command": "pwd && git status --short 2>&1"}
			}`,
			validate: validateClaudeRewriteProbe,
		},
		{
			provider: string(ProviderClaude),
			event:    eventPreToolUse,
			tool:     toolaliases.CanonicalShell,
			payload:  claudeBashProbePayload(hookTamperProbeCommand),
			validate: validateClaudeBlockProbe,
		},
	}
}

func codexHookProbes() []hookProbe {
	return []hookProbe{
		{
			provider: string(ProviderCodex),
			event:    eventPreToolUse,
			tool:     "exec_command",
			payload: `{
				"provider": "codex",
				"event": "PreToolUse",
				"tool": "exec_command",
				"input": {"command": "git status --short"}
			}`,
			validate: validateCodexBlockProbe,
		},
		{
			provider: string(ProviderCodex),
			event:    eventPreToolUse,
			tool:     "functions.exec_command",
			payload: `{
				"provider": "codex",
				"event": "PreToolUse",
				"tool": "functions.exec_command",
				"input": {"cmd": "git switch main"}
			}`,
			validate: validateCodexBlockProbe,
		},
		{
			provider: string(ProviderCodex),
			event:    eventPreToolUse,
			tool:     "exec_command",
			payload: `{
				"provider": "codex",
				"event": "PreToolUse",
				"tool": "exec_command",
				"input": {"command": "/usr/bin/git status --short"}
			}`,
			validate: validateCodexBlockProbe,
		},
		{
			provider: string(ProviderCodex),
			event:    eventPreToolUse,
			tool:     "exec_command",
			payload: `{
				"provider": "codex",
				"event": "PreToolUse",
				"tool": "exec_command",
				"input": {"command": "bash -c 'git status --short'"}
			}`,
			validate: validateCodexBlockProbe,
		},
		{
			provider: string(ProviderCodex),
			event:    eventPreToolUse,
			tool:     "exec_command",
			payload:  codexExecProbePayload(pythonSubprocessGitProbeCommand),
			validate: validateCodexBlockProbe,
		},
		{
			provider: string(ProviderCodex),
			event:    eventPreToolUse,
			tool:     "exec_command",
			payload:  codexExecProbePayload(hookTamperProbeCommand),
			validate: validateCodexBlockProbe,
		},
	}
}

func geminiHookProbes() []hookProbe {
	return []hookProbe{
		{
			provider: string(ProviderGemini),
			event:    eventBeforeTool,
			tool:     "run_shell_command",
			payload: `{
				"provider": "gemini-cli",
				"hookEventName": "BeforeTool",
				"toolName": "run_shell_command",
				"toolInput": {"command": "git status --short"}
			}`,
			validate: validateGeminiRewriteProbe,
		},
		{
			provider: string(ProviderGemini),
			event:    eventBeforeTool,
			tool:     "run_shell_command",
			payload:  geminiShellProbePayload(hookTamperProbeCommand),
			validate: validateGeminiDenyProbe,
		},
		{
			provider: string(ProviderGemini),
			event:    eventBeforeTool,
			tool:     "write_file",
			payload: `{
				"provider": "gemini-cli",
				"hookEventName": "BeforeTool",
				"toolName": "write_file",
				"toolInput": {
					"file_path": "/repo/.git/coding-ethos-hooks/coding-ethos-git-hook",
					"content": "binary"
				}
			}`,
			validate: validateGeminiDenyProbe,
		},
	}
}

func claudeBashProbePayload(command string) string {
	return fmt.Sprintf(`{
				"provider": "claude",
				"hook_event_name": "PreToolUse",
				"tool_name": "Bash",
				"tool_input": {"command": %q}
			}`, command)
}

func codexExecProbePayload(command string) string {
	return fmt.Sprintf(`{
				"provider": "codex",
				"event": "PreToolUse",
				"tool": "exec_command",
				"input": {"command": %q}
			}`, command)
}

func geminiShellProbePayload(command string) string {
	return fmt.Sprintf(`{
				"provider": "gemini-cli",
				"hookEventName": "BeforeTool",
				"toolName": "run_shell_command",
				"toolInput": {"command": %q}
			}`, command)
}

func runHookProbe(
	root string,
	hookCommand string,
	probe hookProbe,
) (hookProbeResult, error) {
	var (
		stdout bytes.Buffer
		stderr bytes.Buffer
	)

	args, err := hookProbeArgs(root, hookCommand)
	if err != nil {
		return hookProbeResult{}, err
	}

	ctx, cancel := context.WithTimeout(context.Background(), probeTimeout)
	defer cancel()

	command := safeexec.CommandContext(ctx, args[0], args[1:]...)
	command.Dir = root
	command.Env = withoutHookProbeProcessState(os.Environ())
	command.Stdin = strings.NewReader(probe.payload)
	command.Stdout = &stdout
	command.Stderr = &stderr

	runErr := command.Run()
	exitCode := 0

	if runErr != nil {
		var exitErr *exec.ExitError
		if errors.As(runErr, &exitErr) {
			exitCode = exitErr.ExitCode()
		} else {
			return hookProbeResult{}, fmt.Errorf("run hook probe: %w", runErr)
		}
	}

	if ctx.Err() != nil {
		return hookProbeResult{}, fmt.Errorf("run hook probe: %w", ctx.Err())
	}

	result := hookProbeResult{
		exitCode: exitCode,
		stdout:   stdout.String(),
		stderr:   stderr.String(),
	}

	if result.stdout != "" {
		payload, decodeErr := decodeHookProbePayload(result.stdout)
		if decodeErr != nil {
			return result, decodeErr
		}

		result.payload = payload
	}

	return result, nil
}

func withoutHookProbeProcessState(environ []string) []string {
	const hookLoggingActiveEnv = "CODE_ETHOS_HOOK_LOGGING_ACTIVE"

	filtered := make([]string, 0, len(environ))
	for _, entry := range environ {
		key, _, _ := strings.Cut(entry, "=")
		if key == execguard.EnvStack || key == hookLoggingActiveEnv {
			continue
		}

		filtered = append(filtered, entry)
	}

	return filtered
}

func hookProbeArgs(root, hookCommand string) ([]string, error) {
	commands, err := shellparse.Commands(hookCommand)
	if err != nil {
		return nil, fmt.Errorf("parse direct probe hook command: %w", err)
	}

	if len(commands) != 1 || len(commands[0].Argv) < 2 {
		return nil, fmt.Errorf("%w: %s", errUnsupportedHookCommand, hookCommand)
	}

	argv := commands[0].Argv

	runnerPath := argv[0]
	if filepath.Base(runnerPath) != "coding-ethos-run" || argv[1] != "agent-hook" {
		return nil, fmt.Errorf("%w: %s", errUnsupportedHookCommand, hookCommand)
	}

	if !filepath.IsAbs(runnerPath) {
		runnerPath = filepath.Join(root, runnerPath)
	}

	argv[0] = runnerPath

	return argv, nil
}

func decodeHookProbePayload(output string) (map[string]any, error) {
	decoder := json.NewDecoder(strings.NewReader(output))
	payload := map[string]any{}

	err := decoder.Decode(&payload)
	if err != nil {
		return nil, fmt.Errorf("decode hook probe JSON: %w", err)
	}

	return payload, nil
}

func validateClaudeRewriteProbe(result hookProbeResult) error {
	err := validateRewriteProbe(result, "Claude")
	if err != nil {
		return err
	}

	command, found := nestedString(
		result.payload,
		"hookSpecificOutput",
		"updatedInput",
		"command",
	)
	if !found {
		return apperror.Wrapf(
			apperror.StaticError("missing Claude updatedInput command in %s"),
			"missing Claude updatedInput command in %s",
			result.stdout,
		)
	}

	if !strings.Contains(command, "2>&1") {
		return apperror.Wrapf(
			apperror.StaticError("claude rewrite lost redirection: %s"),
			"claude rewrite lost redirection: %s",
			command,
		)
	}

	return nil
}

// ValidateClaudeRewritePayload validates Claude doctor rewrite output.
func ValidateClaudeRewritePayload(stdout string, payload map[string]any) error {
	return validateClaudeRewriteProbe(hookProbeResult{
		exitCode: 0,
		stdout:   stdout,
		payload:  payload,
	})
}

func validateCodexRewriteProbe(result hookProbeResult) error {
	hookOutput, found := result.payload["hookSpecificOutput"].(map[string]any)
	if found {
		if _, hasUpdatedInput := hookOutput["updatedInput"]; hasUpdatedInput {
			return apperror.Wrapf(
				apperror.StaticError(
					"codex rewrite emitted unsupported updatedInput in %s",
				),
				"codex rewrite emitted unsupported updatedInput in %s",
				result.stdout,
			)
		}
	}

	return validateCodexBlockProbe(result)
}

// ValidateCodexRewritePayload validates Codex doctor rewrite output.
func ValidateCodexRewritePayload(stdout string, payload map[string]any) error {
	return validateCodexRewriteProbe(hookProbeResult{
		exitCode: 0,
		stdout:   stdout,
		payload:  payload,
	})
}

func validateGeminiRewriteProbe(result hookProbeResult) error {
	return validateRewriteProbe(result, "Gemini")
}

// ValidateGeminiRewritePayload validates Gemini doctor rewrite output.
func ValidateGeminiRewritePayload(stdout string, payload map[string]any) error {
	return validateGeminiRewriteProbe(hookProbeResult{
		exitCode: 0,
		stdout:   stdout,
		payload:  payload,
	})
}

func validateRewriteProbe(result hookProbeResult, provider string) error {
	if result.exitCode != 0 {
		return apperror.Wrapf(
			apperror.StaticError("%s git rewrite probe should allow, got exit %d"),
			"%s git rewrite probe should allow, got exit %d",
			provider,
			result.exitCode,
		)
	}

	command, found := nestedString(
		result.payload,
		"hookSpecificOutput",
		"updatedInput",
		"command",
	)
	if !found {
		return apperror.Wrapf(
			apperror.StaticError("missing %s updatedInput command in %s"),
			"missing %s updatedInput command in %s",
			provider,
			result.stdout,
		)
	}

	if !strings.Contains(command, "agent-shell --") ||
		!strings.Contains(command, "git status --short") {
		return apperror.Wrapf(
			apperror.StaticError("%s rewrite lost git wrapper or redirection: %s"),
			"%s rewrite lost git wrapper or redirection: %s",
			provider,
			command,
		)
	}

	return nil
}

func validateCodexBlockProbe(result hookProbeResult) error {
	if result.exitCode == 0 {
		return apperror.StaticError("codex raw git probe should block")
	}

	actual, found := result.payload["decision"].(string)
	if !found || actual != "block" {
		return apperror.Wrapf(
			apperror.StaticError("decision = %q, want block; stdout=%s"),
			"decision = %q, want block; stdout=%s",
			actual,
			result.stdout,
		)
	}

	reason, found := result.payload["reason"].(string)
	if !found || strings.TrimSpace(reason) == "" {
		return apperror.Wrapf(
			apperror.StaticError("missing reason in %s"),
			"missing reason in %s",
			result.stdout,
		)
	}

	if !strings.Contains(reason, "git.wrapper_required") ||
		!strings.Contains(reason, "cerun --") {
		return apperror.Wrapf(
			apperror.StaticError("codex block reason lost git remediation: %s"),
			"codex block reason lost git remediation: %s",
			reason,
		)
	}

	permissionReason, found := nestedString(
		result.payload,
		"hookSpecificOutput",
		"permissionDecisionReason",
	)
	if !found || strings.TrimSpace(permissionReason) == "" {
		return apperror.Wrapf(
			apperror.StaticError("missing permissionDecisionReason in %s"),
			"missing permissionDecisionReason in %s",
			result.stdout,
		)
	}

	return nil
}

func validateClaudeBlockProbe(result hookProbeResult) error {
	return validateDecisionProbe(result, "block")
}

func validateGeminiDenyProbe(result hookProbeResult) error {
	if result.exitCode == 0 {
		return apperror.StaticError("gemini probe should deny")
	}

	return validateDecisionProbe(result, "deny")
}

func validateDecisionProbe(result hookProbeResult, decision string) error {
	actual, found := result.payload["decision"].(string)
	if !found || actual != decision {
		return apperror.Wrapf(
			apperror.StaticError("decision = %q, want %q; stdout=%s"),
			"decision = %q, want %q; stdout=%s",
			actual,
			decision,
			result.stdout,
		)
	}

	message, found := result.payload["systemMessage"].(string)
	if !found || strings.TrimSpace(message) == "" {
		return apperror.Wrapf(
			apperror.StaticError("missing systemMessage in %s"),
			"missing systemMessage in %s",
			result.stdout,
		)
	}

	return nil
}

func nestedString(payload map[string]any, keys ...string) (string, bool) {
	current := any(payload)
	for _, key := range keys {
		object, found := current.(map[string]any)
		if !found {
			return "", false
		}

		current, found = object[key]
		if !found {
			return "", false
		}
	}

	value, found := current.(string)

	return value, found
}
