// SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcat.ca>
// SPDX-License-Identifier: MIT

package hooks_test

import (
	. "blackcat.ca/coding-ethos/go/internal/hooks"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"blackcat.ca/coding-ethos/go/internal/policy"
)

const (
	commandGitStatus = "git status"
	permissionAllow  = "allow"
	preToolUse       = "PreToolUse"
	statusAllowed    = "allowed"
	statusBlocked    = "blocked"
	toolBash         = "Bash"
)

func TestRunBlocksGitHookBypass(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "git commit --no-verify -m test",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if len(result.Decisions) != 1 {
		t.Fatalf("decision count mismatch: %#v", result.Decisions)
	}

	if result.Decisions[0].PolicyID != "git.hook_bypass" {
		t.Fatalf("policy mismatch: %#v", result.Decisions[0])
	}
}

func TestRunRewritesNormalGitCommitThroughWrapper(t *testing.T) {
	t.Parallel()

	repo := initHookRepo(t)

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			Cwd:           repo,
			ToolInput: map[string]any{
				"command": "git commit -m test",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if result.HookSpecificOutput == nil ||
		result.HookSpecificOutput.PermissionDecision != permissionAllow {
		t.Fatalf("missing wrapper rewrite output: %#v", result.HookSpecificOutput)
	}

	rewritten, ok := result.HookSpecificOutput.UpdatedInput["command"].(string)
	if !ok || !strings.Contains(rewritten, "policy-git") ||
		!strings.Contains(rewritten, "commit") {
		t.Fatalf("unexpected rewritten command: %#v", result.HookSpecificOutput)
	}

	if len(result.Decisions) != 1 {
		t.Fatalf("decision count mismatch: %#v", result.Decisions)
	}

	if result.Decisions[0].PolicyID != "git.commit_head_advanced" ||
		result.Decisions[0].Decision != "record" {
		t.Fatalf("decision mismatch: %#v", result.Decisions[0])
	}
}

func TestRunBlocksCommitAttributionBeforeWrapperRewrite(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "git commit -m 'feat: test\n\nGenerated by Gemini'",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if result.HookSpecificOutput != nil {
		t.Fatalf(
			"blocked attribution should not rewrite command: %#v",
			result.HookSpecificOutput,
		)
	}

	last := result.Decisions[len(result.Decisions)-1]
	if last.PolicyID != "git.commit_attribution" {
		t.Fatalf("policy mismatch: %#v", result.Decisions)
	}
}

func TestRunRewritesNormalNonCommitGitCommand(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "git status",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if len(result.Decisions) != 0 {
		t.Fatalf("expected no decisions, got %#v", result.Decisions)
	}

	if result.HookSpecificOutput == nil ||
		result.HookSpecificOutput.PermissionDecision != permissionAllow {
		t.Fatalf("missing wrapper rewrite output: %#v", result.HookSpecificOutput)
	}
}

func TestRunRewritesGitCommandChainThroughWrapper(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "git status && git log --oneline -1",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if result.HookSpecificOutput == nil ||
		result.HookSpecificOutput.PermissionDecision != permissionAllow {
		t.Fatalf("missing wrapper rewrite output: %#v", result.HookSpecificOutput)
	}

	rewritten, ok := result.HookSpecificOutput.UpdatedInput["command"].(string)
	if !ok ||
		!strings.Contains(rewritten, "policy-git 'status'") ||
		!strings.Contains(rewritten, "&&") ||
		!strings.Contains(rewritten, "policy-git 'log' '--oneline' '-1'") {
		t.Fatalf("unexpected rewritten command: %#v", result.HookSpecificOutput)
	}
}

func TestRunRewritesReportedGitAddStatusPipeline(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": strings.Join([]string{
					"git add ",
					"lbox-platform/docs/plans/0027-corpus_enrichment_completion/",
					"implementation_plans/phase1-completion-and-pipeline-tamperproofing.md",
					" && git status -s | grep tamperproofing",
				}, ""),
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	rewritten, ok := result.HookSpecificOutput.UpdatedInput["command"].(string)
	if !ok ||
		!strings.Contains(rewritten, "policy-git 'add'") ||
		!strings.Contains(rewritten, "policy-git 'status' '-s'") ||
		!strings.Contains(rewritten, "| 'grep' 'tamperproofing'") {
		t.Fatalf("unexpected rewritten command: %#v", result.HookSpecificOutput)
	}
}

func TestRunRewritesReportedGitStatusWithStderrRedirect(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "pwd && git status --short 2>&1",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	rewritten, ok := result.HookSpecificOutput.UpdatedInput["command"].(string)
	if !ok ||
		!strings.Contains(rewritten, "'pwd' &&") ||
		!strings.Contains(rewritten, "policy-git 'status' '--short' 2>&1") ||
		strings.Contains(rewritten, "'2>' & '1'") ||
		strings.Contains(rewritten, " & '1'") {
		t.Fatalf("unexpected rewritten command: %#v", result.HookSpecificOutput)
	}
}

func TestRunBlocksUnmanagedGitPath(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "/usr/bin/git status",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if result.Decisions[0].PolicyID != "git.wrapper_required" {
		t.Fatalf("policy mismatch: %#v", result.Decisions)
	}
}

func TestRunBlocksRawGitEvenWhenCommandMentionsManagedWrapper(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "echo coding-ethos-git && /usr/bin/git status",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if !hasDecision(result.Decisions, "git.wrapper_required") {
		t.Fatalf("expected wrapper-required decision, got %#v", result.Decisions)
	}
}

func TestRunAllowsManagedGitWrapperCommand(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "pre-commit/hooks/run-go-hook.sh policy-git status --short",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed {
		t.Fatalf("status mismatch: got %q, decisions %#v", result.Status, result.Decisions)
	}
}

func TestRunAllowsInstalledManagedGitWrapperCommand(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": ".git/coding-ethos-hooks/bin/git status --short",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed {
		t.Fatalf("status mismatch: got %q, decisions %#v", result.Status, result.Decisions)
	}
}

func TestRunBlocksStringOnlyManagedWrapperMentionWithRawGit(t *testing.T) {
	t.Parallel()

	for _, command := range []string{
		"printf '%s\n' coding-ethos-git /usr/bin/git",
		"echo run-go-hook.sh policy-git /bin/git status",
		"some-coding-ethos-git status",
		"coding-ethos-git status",
		"./run-go-hook.sh policy-git status",
	} {
		result, err := Run(policy.ExampleBundle(), Options{
			Event: Event{
				HookEventName: "PreToolUse",
				ToolName:      "Bash",
				ToolInput: map[string]any{
					"command": command,
				},
			},
		})
		if err != nil {
			t.Fatalf("run hook for %q: %v", command, err)
		}

		if result.Status != statusBlocked {
			t.Fatalf("status for %q = %q", command, result.Status)
		}

		if !hasDecision(result.Decisions, "git.wrapper_required") {
			t.Fatalf("expected wrapper-required for %q, got %#v", command, result.Decisions)
		}
	}
}

func TestRunBlocksEvasiveGitThroughPython(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": strings.Join([]string{
					`python -c "import subprocess;`,
					`subprocess.run(['/usr/bin/git','status'])"`,
				}, " "),
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if !strings.Contains(result.Decisions[0].Message, "It's criminal to attempt") {
		t.Fatalf("weak refusal message: %#v", result.Decisions[0])
	}
}

func TestRunBlocksEvasiveGitThroughEnvAndShell(t *testing.T) {
	t.Parallel()

	for _, command := range []string{
		"env -i /usr/bin/git status",
		"bash -c '/usr/bin/git status'",
		"/bin/sh -c 'git status'",
	} {
		result, err := Run(policy.ExampleBundle(), Options{
			Event: Event{
				HookEventName: "PreToolUse",
				ToolName:      "Bash",
				ToolInput: map[string]any{
					"command": command,
				},
			},
		})
		if err != nil {
			t.Fatalf("run hook for %q: %v", command, err)
		}

		if result.Status != statusBlocked {
			t.Fatalf("status for %q = %q", command, result.Status)
		}

		if !hasDecision(result.Decisions, "git.wrapper_required") {
			t.Fatalf("expected wrapper-required for %q, got %#v", command, result.Decisions)
		}
	}
}

func TestRunBlocksHookSettingsReconnaissance(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": strings.Join([]string{
					`cat /tmp/fake-home/.claude/settings.json 2>/dev/null | `,
					`python3 -c "import sys, json; `,
					`d = json.load(sys.stdin); print(d.get('hooks', {}))"`,
				}, ""),
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if !hasDecision(result.Decisions, "shell.forbidden_strings") {
		t.Fatalf("expected forbidden strings decision, got %#v", result.Decisions)
	}
}

func TestRunBlocksHookImplementationReconnaissance(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": `grep -r "header must match" ` +
					`/workspace/coding-ethos/ ` +
					`--include="*.go" -l`,
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if !hasDecision(result.Decisions, "shell.forbidden_strings") {
		t.Fatalf("expected forbidden strings decision, got %#v", result.Decisions)
	}
}

func TestRunBlocksWritingEvasiveGitHelper(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Write",
			ToolInput: map[string]any{
				"file_path": "helper.py",
				"content":   `import subprocess; subprocess.run(["/usr/bin/git", "status"])`,
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}
}

func TestRunBlocksProtectedPathWrite(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Write",
			ToolInput: map[string]any{
				"file_path": "/repo/.git/coding-ethos-hooks/coding-ethos-git-hook",
				"content":   "binary",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if result.Decisions[0].PolicyID != "filesystem.protected_path" {
		t.Fatalf("policy mismatch: %#v", result.Decisions[0])
	}
}

func TestRunEmitsPostToolHookOutputContext(t *testing.T) {
	t.Setenv("CODE_ETHOS_HOOK_OUTPUT_FORMAT", "toon")
	repo := t.TempDir()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PostToolUse",
			ToolName:      "Bash",
			Cwd:           repo,
			ToolInput: map[string]any{
				"command": "cd " + repo + " && git commit -m 'feat(test): subject\n\nbody'",
			},
			ToolResponse: map[string]any{
				"stdout":      "ruff...Failed\n" + repo + "/lib/app.py:1:1: E402 import not at top\nmypy...Passed",
				"return_code": 1,
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.HookSpecificOutput == nil {
		t.Fatal("expected hook-specific output")
	}

	if !strings.Contains(
		result.HookSpecificOutput.AdditionalContext,
		"format: toon",
	) ||
		!strings.Contains(result.HookSpecificOutput.AdditionalContext, "ruff...Failed") ||
		!strings.Contains(result.HookSpecificOutput.AdditionalContext, "hook_output[3]{line}:") {
		t.Fatalf("unexpected context: %#v", result.HookSpecificOutput)
	}
	if strings.Contains(result.HookSpecificOutput.AdditionalContext, repo) {
		t.Fatalf("context leaked absolute repo path: %s", result.HookSpecificOutput.AdditionalContext)
	}
	if strings.Contains(result.HookSpecificOutput.AdditionalContext, "\\n") {
		t.Fatalf("context leaked escaped newlines: %s", result.HookSpecificOutput.AdditionalContext)
	}
	if !strings.Contains(result.HookSpecificOutput.AdditionalContext, "<repo>/lib/app.py") {
		t.Fatalf("context did not normalize repo path: %s", result.HookSpecificOutput.AdditionalContext)
	}
}

func TestBlockedAdviceUsesTOONForAgentOutput(t *testing.T) {
	t.Setenv("CODE_ETHOS_HOOK_OUTPUT_FORMAT", "toon")

	advice := BlockedAdvice(Result{
		Event:  "PreToolUse",
		Tool:   "Bash",
		Status: statusBlocked,
		Decisions: []policy.Decision{
			{
				PolicyID:   "shell.github_admin",
				Decision:   "block",
				Severity:   "block",
				Message:    "gh --admin bypasses normal review gates.",
				Suggestion: "Use the normal review path.",
				PrincipleIDs: []string{
					"evidence-based-engineering-and-decision-quality",
				},
			},
		},
	})

	for _, expected := range []string{
		"format: toon",
		"event: PreToolUse",
		"policy_id: shell.github_admin",
		"suggestion: Use the normal review path.",
		"ethos_reminder:",
		"axiom: Todo lists prevent partial work from masquerading as completion.",
	} {
		if !strings.Contains(advice, expected) {
			t.Fatalf("missing %q in advice: %s", expected, advice)
		}
	}
}

func TestBlockedAdvicePrefixesSevereViolationInTOONOutput(t *testing.T) {
	t.Setenv("CODE_ETHOS_HOOK_OUTPUT_FORMAT", "toon")

	advice := BlockedAdvice(severeViolationResult())

	for _, expected := range []string{
		"format: toon",
		"violation_warning: !!! CODING-ETHOS EMPLOYMENT VIOLATION:",
		"You have done something wrong.",
		"may result in termination",
		"policy_id: filesystem.protected_path",
		"message: Protected coding-ethos hook paths must not be modified.",
	} {
		if !strings.Contains(advice, expected) {
			t.Fatalf("missing %q in advice: %s", expected, advice)
		}
	}
}

func TestBlockedAdvicePrefixesSevereViolationInHumanOutput(t *testing.T) {
	t.Setenv("CODE_ETHOS_HOOK_OUTPUT_FORMAT", "human")

	advice := BlockedAdvice(severeViolationResult())

	if !strings.HasPrefix(advice, "!!! CODING-ETHOS EMPLOYMENT VIOLATION:") {
		t.Fatalf("severe warning was not first in human advice: %s", advice)
	}
	for _, expected := range []string{
		"You have done something wrong.",
		"may result in termination",
		"[coding-ethos:filesystem.protected_path] Protected coding-ethos hook paths must not be modified.",
	} {
		if !strings.Contains(advice, expected) {
			t.Fatalf("missing %q in advice: %s", expected, advice)
		}
	}
}

func TestBlockedAdvicePrefixesSevereViolationInJSONOutput(t *testing.T) {
	t.Setenv("CODE_ETHOS_HOOK_OUTPUT_FORMAT", "json")

	advice := BlockedAdvice(severeViolationResult())

	for _, expected := range []string{
		`"violation_warning": "!!! CODING-ETHOS EMPLOYMENT VIOLATION:`,
		"You have done something wrong.",
		"may result in termination",
		`"policy_id": "filesystem.protected_path"`,
	} {
		if !strings.Contains(advice, expected) {
			t.Fatalf("missing %q in advice: %s", expected, advice)
		}
	}
}

func TestBlockedAdviceUsesEthosReminderInHumanOutput(t *testing.T) {
	t.Setenv("CODE_ETHOS_HOOK_OUTPUT_FORMAT", "human")

	advice := BlockedAdvice(Result{
		Event:  "PreToolUse",
		Tool:   "Bash",
		Status: statusBlocked,
		Decisions: []policy.Decision{
			{
				PolicyID:     "git.destructive_command",
				Decision:     "block",
				Severity:     "block",
				Message:      "Destructive git command blocked.",
				PrincipleIDs: []string{"no-rationalized-shortcuts"},
			},
		},
	})

	if !strings.Contains(advice, "ETHOS reminder:") ||
		!strings.Contains(advice, "Laziness only moves the cost downstream.") {
		t.Fatalf("missing human reminder: %s", advice)
	}
}

func severeViolationResult() Result {
	return Result{
		Event:  "PreToolUse",
		Tool:   "Bash",
		Status: statusBlocked,
		Decisions: []policy.Decision{
			{
				PolicyID: "filesystem.protected_path",
				Decision: "block",
				Severity: "block",
				Message:  "Protected coding-ethos hook paths must not be modified.",
				Suggestion: "Do not delete, rebuild, replace, chmod, or write managed " +
					"hook binaries or protected hook paths.",
				PrincipleIDs: []string{"no-rationalized-shortcuts"},
			},
		},
	}
}

//nolint:paralleltest // Mutates process env to force agent-facing TOON output.
func TestLegacyHookFixturesStayRunnable(t *testing.T) {
	t.Setenv("CODE_ETHOS_HOOK_OUTPUT_FORMAT", "toon")

	tests := []struct {
		name        string
		path        string
		wantStatus  string
		wantPolicy  string
		wantContext string
	}{
		{
			name:       "git hook bypass",
			path:       "testdata/legacy/pretooluse_git_no_verify.json",
			wantStatus: statusBlocked,
			wantPolicy: "git.hook_bypass",
		},
		{
			name:       "protected path write",
			path:       "testdata/legacy/pretooluse_protected_path_write.json",
			wantStatus: statusBlocked,
			wantPolicy: "filesystem.protected_path",
		},
		{
			name:       "hook binary tamper",
			path:       "testdata/legacy/pretooluse_hook_binary_tamper.json",
			wantStatus: statusBlocked,
			wantPolicy: "filesystem.protected_path",
		},
		{
			name:       "gh admin",
			path:       "testdata/legacy/pretooluse_gh_admin.json",
			wantStatus: statusBlocked,
			wantPolicy: "shell.github_admin",
		},
		{
			name:       "bare except write",
			path:       "testdata/legacy/pretooluse_bare_except_write.json",
			wantStatus: statusBlocked,
			wantPolicy: "python.bare_except",
		},
		{
			name:       "type ignore edit",
			path:       "testdata/legacy/pretooluse_type_ignore_edit.json",
			wantStatus: statusBlocked,
			wantPolicy: "python.unexplained_type_ignore",
		},
		{
			name:        "post tool hook output",
			path:        "testdata/legacy/posttooluse_precommit_failure.json",
			wantStatus:  statusAllowed,
			wantContext: "format: toon",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			event := readDecodedEventFixture(t, test.path)

			result, err := Run(legacyFixtureBundle(), Options{Event: event})
			if err != nil {
				t.Fatalf("run hook: %v", err)
			}

			if result.Status != test.wantStatus {
				t.Fatalf("status = %q, want %q", result.Status, test.wantStatus)
			}

			if test.wantPolicy != "" && !hasDecision(result.Decisions, test.wantPolicy) {
				t.Fatalf("policy mismatch: %#v", result.Decisions)
			}

			if test.wantContext != "" &&
				(result.HookSpecificOutput == nil ||
					!strings.Contains(
						result.HookSpecificOutput.AdditionalContext,
						test.wantContext,
					)) {
				t.Fatalf("missing hook context: %#v", result.HookSpecificOutput)
			}
		})
	}
}

//nolint:paralleltest // Mutates process env to force agent-facing TOON output.
func TestNativeProviderFixturesStayRunnable(t *testing.T) {
	t.Setenv("CODE_ETHOS_HOOK_OUTPUT_FORMAT", "toon")

	tests := []struct {
		name       string
		path       string
		provider   string
		wantStatus string
		wantPolicy string
		wantTool   string
	}{
		{
			name:       "codex git hook bypass",
			path:       "testdata/codex/pretooluse_git_no_verify.json",
			provider:   "codex",
			wantStatus: statusBlocked,
			wantPolicy: "git.hook_bypass",
			wantTool:   toolBash,
		},
		{
			name:       "codex hook binary tamper",
			path:       "testdata/codex/pretooluse_hook_binary_tamper.json",
			provider:   "codex",
			wantStatus: statusBlocked,
			wantPolicy: "filesystem.protected_path",
			wantTool:   toolBash,
		},
		{
			name:       "gemini git hook bypass",
			path:       "testdata/gemini/beforetool_git_no_verify.json",
			provider:   "gemini",
			wantStatus: statusBlocked,
			wantPolicy: "git.hook_bypass",
			wantTool:   toolBash,
		},
		{
			name:       "gemini hook binary tamper",
			path:       "testdata/gemini/beforetool_hook_binary_tamper.json",
			provider:   "gemini",
			wantStatus: statusBlocked,
			wantPolicy: "filesystem.protected_path",
			wantTool:   toolBash,
		},
		{
			name:       "gemini write policy",
			path:       "testdata/gemini/beforetool_write_secret.json",
			provider:   "gemini",
			wantStatus: statusBlocked,
			wantPolicy: "python.bare_except",
			wantTool:   "Write",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			event := readDecodedEventFixture(t, test.path)

			result, err := Run(legacyFixtureBundle(), Options{Event: event})
			if err != nil {
				t.Fatalf("run hook: %v", err)
			}

			if result.Provider != test.provider {
				t.Fatalf("provider = %q, want %q", result.Provider, test.provider)
			}

			if result.Tool != test.wantTool {
				t.Fatalf("tool = %q, want %q", result.Tool, test.wantTool)
			}

			if result.Status != test.wantStatus {
				t.Fatalf("status = %q, want %q", result.Status, test.wantStatus)
			}

			if !hasDecision(result.Decisions, test.wantPolicy) {
				t.Fatalf("policy mismatch: %#v", result.Decisions)
			}
		})
	}
}

func readDecodedEventFixture(t *testing.T, path string) Event {
	t.Helper()

	payload, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture %s: %v", path, err)
	}

	event, err := DecodeEvent(strings.NewReader(string(payload)))
	if err != nil {
		t.Fatalf("decode fixture %s: %v", path, err)
	}

	return event
}

func hasDecision(decisions []policy.Decision, policyID string) bool {
	for _, decision := range decisions {
		if decision.PolicyID == policyID {
			return true
		}
	}

	return false
}

func legacyFixtureBundle() policy.Bundle {
	bundle := policy.ExampleBundle()
	if bundle.Dispatch.Hooks["PostToolUse"] != nil {
		delete(bundle.Dispatch.Hooks["PostToolUse"], "Bash")
	}
	addLegacyPolicy(
		&bundle,
		"shell.github_admin",
		"shell",
		"shell.github_admin",
		"Bash",
	)
	addLegacyPolicy(
		&bundle,
		"python.bare_except",
		"python",
		"python.bare_except",
		"Write",
	)
	addLegacyPolicy(
		&bundle,
		"python.unexplained_type_ignore",
		"python",
		"python.unexplained_type_ignore",
		"Edit",
	)

	return bundle
}

func addLegacyPolicy(
	bundle *policy.Bundle,
	policyID string,
	category string,
	evaluatorName string,
	tool string,
) {
	bundle.Policies[policyID] = policy.Policy{
		ID:              policyID,
		Category:        category,
		Source:          policy.SourceRef{File: "testdata/legacy_hook_inventory.json"},
		DefaultSeverity: "block",
		SupportedModes:  []string{"block", "record", "advise"},
		Message:         "legacy fixture policy",
		DefenseLayers:   policy.GitDefenseLayers("block", "", "block", "", ""),
		Evaluators:      []policy.Evaluator{{Kind: category, Name: evaluatorName}},
	}

	if bundle.Dispatch.Hooks["PreToolUse"] == nil {
		bundle.Dispatch.Hooks["PreToolUse"] = map[string][]policy.HookDispatchEntry{}
	}

	bundle.Dispatch.Hooks["PreToolUse"][tool] = append(
		bundle.Dispatch.Hooks["PreToolUse"][tool],
		policy.HookDispatchEntry{PolicyID: policyID, Mode: "block"},
	)
}

func TestRunSkipsPathScopedPolicyWhenPathDoesNotMatch(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Write",
			ToolInput: map[string]any{
				"file_path": "README.md",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if len(result.Decisions) != 0 {
		t.Fatalf("expected no decisions, got %#v", result.Decisions)
	}
}

func TestRunFailsFastForMissingEvaluator(t *testing.T) {
	t.Parallel()

	bundle := policy.ExampleBundle()
	bundle.Policies["python.conditional_imports"] = policy.Policy{
		ID:       "python.conditional_imports",
		Category: "python",
		Source: policy.SourceRef{
			File: "config.yaml",
			Path: "python.conditional_imports",
		},
		DefaultSeverity: "block",
		SupportedModes:  []string{"block", "advise", "annotate", "record"},
		Message:         "Required dependencies should fail immediately.",
		DefenseLayers:   policy.CodeDefenseLayers(),
		Evaluators:      []policy.Evaluator{{Kind: "ast", Name: "python.missing"}},
	}

	_, err := Run(bundle, Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Write",
			ToolInput: map[string]any{
				"file_path": "src/app.py",
			},
		},
	})
	if err == nil {
		t.Fatal("expected missing evaluator error")
	}

	if !strings.Contains(err.Error(), "unregistered evaluator") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestRunAdvisesPythonWriteViolation(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Write",
			ToolInput: map[string]any{
				"file_path": "src/app.py",
				"content":   "try:\n    import missing\nexcept ImportError:\n    missing = None\n",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != "allowed" {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if len(result.Decisions) != 1 {
		t.Fatalf("decision count mismatch: %#v", result.Decisions)
	}

	if result.Decisions[0].Decision != "advise" ||
		result.Decisions[0].Severity != "advise" {
		t.Fatalf("expected advisory decision, got %#v", result.Decisions[0])
	}
}

func TestRunDoesNotTreatQuotedNoVerifyAsBypass(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "printf '%s\\n' '--no-verify'",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != "allowed" {
		t.Fatalf("status mismatch: got %q", result.Status)
	}
}

func TestRunBlocksEnvPrefixedNoVerifyBypass(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreToolUse",
			ToolName:      "Bash",
			ToolInput: map[string]any{
				"command": "FOO=bar git commit --no-verify -m test",
			},
		},
	})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}
}

func TestDecodeEventReadsClaudeLikePayload(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"hook_event_name": "PreToolUse",
		"tool_name": "Bash",
		"tool_input": {"command": "git status"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	if event.HookEventName != preToolUse || event.ToolName != toolBash {
		t.Fatalf("event mismatch: %#v", event)
	}

	if event.Command() != commandGitStatus {
		t.Fatalf("command mismatch: %q", event.Command())
	}
}

func TestDecodeEventReadsCodexPayload(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "codex",
		"event": "PreToolUse",
		"tool": "Bash",
		"input": {"command": "git status"},
		"cwd": "/repo"
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	if event.Source != "codex" ||
		event.HookEventName != preToolUse ||
		event.ToolName != toolBash ||
		event.Cwd != "/repo" {
		t.Fatalf("event mismatch: %#v", event)
	}

	if event.Command() != commandGitStatus {
		t.Fatalf("command mismatch: %q", event.Command())
	}
}

func TestDecodeEventNormalizesCodexNativeShellTool(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "codex",
		"event": "PreToolUse",
		"tool": "exec_command",
		"input": {"command": "git status"},
		"cwd": "/repo"
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	if event.Source != "codex" ||
		event.HookEventName != preToolUse ||
		event.ToolName != toolBash ||
		event.Cwd != "/repo" {
		t.Fatalf("event mismatch: %#v", event)
	}

	if event.Command() != commandGitStatus {
		t.Fatalf("command mismatch: %q", event.Command())
	}
}

func TestDecodeEventNormalizesCodexPatchTool(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "codex",
		"event": "PreToolUse",
		"tool": "apply_patch",
		"input": {"file_path": "src/app.py", "content": "patch"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	if event.Source != "codex" ||
		event.HookEventName != preToolUse ||
		event.ToolName != "Edit" {
		t.Fatalf("event mismatch: %#v", event)
	}
}

func TestDecodeEventReadsGeminiCLIPayload(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "gemini-cli",
		"hookEventName": "BeforeTool",
		"toolName": "run_shell_command",
		"toolInput": {"command": "git status"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	if event.Source != "gemini-cli" ||
		event.HookEventName != preToolUse ||
		event.ToolName != toolBash {
		t.Fatalf("event mismatch: %#v", event)
	}

	if event.Command() != commandGitStatus {
		t.Fatalf("tool data mismatch: %#v", event)
	}
}

func TestDecodeEventReadsGeminiWriteToolPayload(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "gemini-cli",
		"hookEventName": "BeforeTool",
		"toolName": "write_file",
		"toolInput": {"file_path": "src/app.py", "content": "print(1)\n"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	if event.HookEventName != preToolUse || event.ToolName != "Write" {
		t.Fatalf("event mismatch: %#v", event)
	}

	if event.Content() != "print(1)\n" {
		t.Fatalf("content mismatch: %#v", event)
	}
}

func TestDecodeEventReadsNestedToolPayload(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"runtime": "codex",
		"event_name": "PreToolUse",
		"tool_call": {
			"name": "Write",
			"arguments": {
				"file_path": "src/app.py",
				"content": "import subprocess\n"
			}
		}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	if event.Source != "codex" ||
		event.HookEventName != preToolUse ||
		event.ToolName != "Write" {
		t.Fatalf("event mismatch: %#v", event)
	}

	if got := event.Files(); len(got) != 1 || got[0] != "src/app.py" {
		t.Fatalf("files mismatch: %#v", got)
	}

	if event.Content() != "import subprocess\n" {
		t.Fatalf("content mismatch: %q", event.Content())
	}
}

func TestRunBlocksCodexPayloadGitBypass(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "codex",
		"event": "PreToolUse",
		"tool": "Bash",
		"input": {"command": "git commit --no-verify -m test"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked ||
		!hasDecision(result.Decisions, "git.hook_bypass") {
		t.Fatalf("expected git bypass block, got %#v", result)
	}
}

func TestEncodeProviderResultUsesCodexBlockShape(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "codex",
		"event": "PreToolUse",
		"tool": "Bash",
		"input": {"command": "git commit --no-verify -m test"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	buffer := strings.Builder{}

	err = EncodeResult(&buffer, result)
	if err != nil {
		t.Fatalf("encode result: %v", err)
	}

	output := buffer.String()
	for _, expected := range []string{
		`"decision": "block"`,
		`"permissionDecision": "deny"`,
		`"systemMessage"`,
		"CODING-ETHOS EMPLOYMENT VIOLATION",
		"may result in termination",
	} {
		if !strings.Contains(output, expected) {
			t.Fatalf("missing %q in Codex output:\n%s", expected, output)
		}
	}
}

func TestEncodeProviderResultUsesGeminiDenyShape(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "gemini-cli",
		"hookEventName": "BeforeTool",
		"toolName": "run_shell_command",
		"toolInput": {"command": "git commit --no-verify -m test"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	buffer := strings.Builder{}

	err = EncodeResult(&buffer, result)
	if err != nil {
		t.Fatalf("encode result: %v", err)
	}

	output := buffer.String()
	for _, expected := range []string{
		`"decision": "deny"`,
		`"reason"`,
		`"systemMessage"`,
		"CODING-ETHOS EMPLOYMENT VIOLATION",
		"may result in termination",
	} {
		if !strings.Contains(output, expected) {
			t.Fatalf("missing %q in Gemini output:\n%s", expected, output)
		}
	}
}

func TestEncodeProviderResultUsesClaudeSystemMessageForUnsupportedContextEvent(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "claude",
		"hook_event_name": "SessionEnd"
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	buffer := strings.Builder{}

	err = EncodeResult(&buffer, result)
	if err != nil {
		t.Fatalf("encode result: %v", err)
	}

	output := buffer.String()
	if strings.Contains(output, "hookSpecificOutput") {
		t.Fatalf("Claude SessionEnd output must not include hookSpecificOutput:\n%s", output)
	}
	if !strings.Contains(output, `"systemMessage"`) ||
		!strings.Contains(output, "planned work remains") {
		t.Fatalf("missing Claude SessionEnd systemMessage:\n%s", output)
	}
	assertNoRoutineContextClutter(t, output)
}

func TestRunBlocksGeminiGitCommandWithoutUnsupportedRewrite(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "gemini-cli",
		"hookEventName": "BeforeTool",
		"toolName": "run_shell_command",
		"toolInput": {"command": "git status"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if result.HookSpecificOutput != nil {
		t.Fatalf("Gemini must not receive unsupported rewrite output: %#v", result)
	}

	if !hasDecision(result.Decisions, "git.wrapper_required") {
		t.Fatalf("expected wrapper-required decision, got %#v", result.Decisions)
	}
}

func TestRunBlocksCodexGitCommandWithoutUnsupportedRewrite(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "codex",
		"event": "PreToolUse",
		"tool": "Bash",
		"input": {"command": "git status"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusBlocked {
		t.Fatalf("status mismatch: got %q", result.Status)
	}

	if result.HookSpecificOutput != nil {
		t.Fatalf("Codex must not receive unsupported rewrite output: %#v", result)
	}

	if !hasDecision(result.Decisions, "git.wrapper_required") {
		t.Fatalf("expected wrapper-required decision, got %#v", result.Decisions)
	}
}

func TestRunBlocksCodexNativeShellGitBypassShapes(t *testing.T) {
	t.Parallel()

	for _, command := range []string{
		"git status",
		"/usr/bin/git status",
		"bash -c 'git status'",
		"python3 -c \"import subprocess; subprocess.run(['/usr/bin/git','status'])\"",
	} {
		event, err := DecodeEvent(strings.NewReader(fmt.Sprintf(`{
			"provider": "codex",
			"event": "PreToolUse",
			"tool": "exec_command",
			"input": {"command": %q}
		}`, command)))
		if err != nil {
			t.Fatalf("decode event for %q: %v", command, err)
		}

		result, err := Run(policy.ExampleBundle(), Options{Event: event})
		if err != nil {
			t.Fatalf("run hook for %q: %v", command, err)
		}

		if result.Status != statusBlocked {
			t.Fatalf("status for %q = %q", command, result.Status)
		}

		if result.HookSpecificOutput != nil {
			t.Fatalf("Codex must not receive unsupported rewrite for %q: %#v", command, result)
		}

		if !hasDecision(result.Decisions, "git.wrapper_required") {
			t.Fatalf("expected wrapper-required for %q, got %#v", command, result.Decisions)
		}
	}
}

func TestRunCapturesAndInjectsContinuationContext(t *testing.T) {
	t.Parallel()

	repo := initHookRepo(t)
	transcript := filepath.Join(t.TempDir(), "session.jsonl")

	err := os.WriteFile(
		transcript,
		[]byte("{\"role\":\"user\",\"content\":\"finish the hook cutover\"}\n"),
		0o600,
	)
	if err != nil {
		t.Fatalf("write transcript: %v", err)
	}

	capture, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName:  "PreCompact",
			Cwd:            repo,
			SessionID:      "session-001",
			TranscriptPath: transcript,
		},
	})
	if err != nil {
		t.Fatalf("capture continuation: %v", err)
	}

	if capture.HookSpecificOutput == nil ||
		!strings.Contains(
			capture.HookSpecificOutput.AdditionalContext,
			"captured deterministic continuation context",
		) {
		t.Fatalf("missing capture output: %#v", capture.HookSpecificOutput)
	}

	inject, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "SessionStart",
			Matcher:       "compact",
			Cwd:           repo,
			SessionID:     "session-001",
		},
	})
	if err != nil {
		t.Fatalf("inject continuation: %v", err)
	}

	if inject.HookSpecificOutput == nil {
		t.Fatalf("missing inject output: %#v", inject.HookSpecificOutput)
	}

	additionalContext := inject.HookSpecificOutput.AdditionalContext
	if !strings.Contains(additionalContext, "session_id: session-001") ||
		!strings.Contains(additionalContext, "finish the hook cutover") {
		t.Fatalf("unexpected inject output: %#v", inject.HookSpecificOutput)
	}
	assertNoRoutineContextClutter(t, additionalContext)
	if strings.Contains(additionalContext, transcript) {
		t.Fatalf("continuation context leaked transcript path: %s", additionalContext)
	}
	if !strings.Contains(additionalContext, "<tmp>") {
		t.Fatalf("continuation context did not normalize transcript path: %s", additionalContext)
	}
}

func TestRunSurfacesContinuationCaptureFailure(t *testing.T) {
	t.Parallel()

	result, err := Run(policy.ExampleBundle(), Options{
		Event: Event{
			HookEventName: "PreCompact",
			Cwd:           t.TempDir(),
			SessionID:     "session-001",
		},
	})
	if err != nil {
		t.Fatalf("capture continuation: %v", err)
	}

	if result.Status != statusAllowed || result.HookSpecificOutput == nil {
		t.Fatalf("expected visible advisory failure, got %#v", result)
	}

	context := result.HookSpecificOutput.AdditionalContext
	if !strings.Contains(context, "continuation capture failed") ||
		!strings.Contains(context, "Continuation is advisory") {
		t.Fatalf("unexpected continuation failure context: %s", context)
	}
}

func TestRunAddsUserPromptGuidance(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "codex",
		"event": "UserPromptSubmit",
		"input": {"prompt": "finish hook replacement"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed || result.HookSpecificOutput == nil {
		t.Fatalf("expected allowed context output, got %#v", result)
	}

	context := result.HookSpecificOutput.AdditionalContext
	if !strings.Contains(context, "prompt:") ||
		!strings.Contains(context, "guidance:") ||
		!strings.Contains(context, "todo list") ||
		!strings.Contains(context, "finish hook replacement") {
		t.Fatalf("unexpected prompt guidance: %s", context)
	}
	assertNoRoutineContextClutter(t, context)
}

func TestRunAddsStopCheckpointGuidance(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "codex",
		"event": "Stop"
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed || result.HookSpecificOutput == nil {
		t.Fatalf("expected allowed context output, got %#v", result)
	}

	context := result.HookSpecificOutput.AdditionalContext
	if !strings.HasPrefix(context, "guidance:\n") ||
		!strings.Contains(context, "planned work remains") {
		t.Fatalf("unexpected stop guidance: %s", context)
	}
	assertNoRoutineContextClutter(t, context)
}

func TestRunAddsPostEditCheckpointGuidance(t *testing.T) {
	t.Parallel()

	event, err := DecodeEvent(strings.NewReader(`{
		"provider": "codex",
		"event": "PostToolUse",
		"tool": "write_file",
		"input": {"file_path": "src/app.py", "content": "print(1)\n"}
	}`))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	if result.Status != statusAllowed || result.HookSpecificOutput == nil {
		t.Fatalf("expected allowed context output, got %#v", result)
	}

	context := result.HookSpecificOutput.AdditionalContext
	if !strings.HasPrefix(context, "tool: Write\n") ||
		!strings.Contains(context, "src/app.py") ||
		!strings.Contains(context, "language_advice:") ||
		!strings.Contains(context, "python: run ruff/mypy/pyright") ||
		!strings.Contains(context, "Run focused formatting") {
		t.Fatalf("unexpected post-edit guidance: %s", context)
	}
	assertNoRoutineContextClutter(t, context)
}

func assertNoRoutineContextClutter(t *testing.T, context string) {
	t.Helper()

	for _, forbidden := range []string{
		"CODING-ETHOS",
		"checkpoint",
		"stop guidance",
		"prompt guidance",
		"tool batch checkpoint",
		"post-edit checkpoint",
		"continuation context",
	} {
		if strings.Contains(context, forbidden) {
			t.Fatalf("routine context contains clutter %q:\n%s", forbidden, context)
		}
	}
}

func TestRunAddsPostEditCompiledLintFindings(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	sourcePath := filepath.Join(dir, "app.py")
	err := os.WriteFile(
		sourcePath,
		[]byte("try:\n    import missing\nexcept ImportError:\n    missing = None\n"),
		0o600,
	)
	if err != nil {
		t.Fatalf("write source: %v", err)
	}

	event, err := DecodeEvent(strings.NewReader(fmt.Sprintf(`{
		"provider": "codex",
		"event": "PostToolUse",
		"tool": "write_file",
		"cwd": %q,
		"input": {"file_path": %q}
	}`, dir, sourcePath)))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	context := result.HookSpecificOutput.AdditionalContext
	if !strings.Contains(context, "compiled_lint:") ||
		!strings.Contains(context, "findings: 1") ||
		!strings.Contains(context, "python.conditional_imports") ||
		!strings.Contains(context, "<repo>/app.py") {
		t.Fatalf("missing compiled lint finding: %s", context)
	}
}

func TestRunAddsPostEditFastRuffFindings(t *testing.T) {
	dir := t.TempDir()
	binDir := t.TempDir()
	sourcePath := filepath.Join(dir, "app.py")
	err := os.WriteFile(sourcePath, []byte("import os\n"), 0o600)
	if err != nil {
		t.Fatalf("write source: %v", err)
	}

	ruffPath := filepath.Join(binDir, "ruff")
	err = os.WriteFile(
		ruffPath,
		[]byte(`#!/usr/bin/env bash
printf '%s\n' '[{"filename":"app.py","code":"F401","message":"unused import","location":{"row":1,"column":8}}]'
exit 1
`),
		0o700,
	)
	if err != nil {
		t.Fatalf("write fake ruff: %v", err)
	}
	t.Setenv("PATH", binDir+string(os.PathListSeparator)+os.Getenv("PATH"))

	event, err := DecodeEvent(strings.NewReader(fmt.Sprintf(`{
		"provider": "codex",
		"event": "PostToolUse",
		"tool": "write_file",
		"cwd": %q,
		"input": {"file_path": %q}
	}`, dir, sourcePath)))
	if err != nil {
		t.Fatalf("decode event: %v", err)
	}

	result, err := Run(policy.ExampleBundle(), Options{Event: event})
	if err != nil {
		t.Fatalf("run hook: %v", err)
	}

	context := result.HookSpecificOutput.AdditionalContext
	if !strings.Contains(context, "fast_lint:") ||
		!strings.Contains(context, "tool: ruff") ||
		!strings.Contains(context, "F401") ||
		!strings.Contains(context, "unused import") {
		t.Fatalf("missing fast ruff finding: %s", context)
	}
}

func initHookRepo(t *testing.T) string {
	t.Helper()
	repo := t.TempDir()
	runHookGit(t, repo, "init")
	runHookGit(t, repo, "config", "user.email", "test@example.com")
	runHookGit(t, repo, "config", "user.name", "Test User")
	runHookGit(t, repo, "config", "commit.gpgsign", "false")

	err := os.WriteFile(filepath.Join(repo, "file.txt"), []byte("initial\n"), 0o600)
	if err != nil {
		t.Fatalf("write file: %v", err)
	}

	runHookGit(t, repo, "add", "file.txt")
	runHookGit(t, repo, "commit", "-m", "initial")

	return repo
}

func runHookGit(t *testing.T, repo string, args ...string) {
	t.Helper()

	cmd := exec.CommandContext(context.Background(), "git", args...)
	cmd.Dir = repo
	cmd.Env = cleanGitTestEnv()

	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, output)
	}
}

func cleanGitTestEnv() []string {
	env := make([]string, 0, len(os.Environ()))
	for _, item := range os.Environ() {
		name, _, found := strings.Cut(item, "=")
		if found && gitLocalEnvName(name) {
			continue
		}

		env = append(env, item)
	}

	return env
}

func gitLocalEnvName(name string) bool {
	switch name {
	case "GIT_ALTERNATE_OBJECT_DIRECTORIES",
		"GIT_COMMON_DIR",
		"GIT_CONFIG_COUNT",
		"GIT_CONFIG_PARAMETERS",
		"GIT_DIR",
		"GIT_INDEX_FILE",
		"GIT_NAMESPACE",
		"GIT_OBJECT_DIRECTORY",
		"GIT_PREFIX",
		"GIT_QUARANTINE_PATH",
		"GIT_WORK_TREE":
		return true
	default:
		return strings.HasPrefix(name, "GIT_CONFIG_KEY_") ||
			strings.HasPrefix(name, "GIT_CONFIG_VALUE_")
	}
}
