# SPDX-FileCopyrightText: 2026 Blackcat Informatics(R) Inc. <paudley@blackcat.ca>
# SPDX-License-Identifier: AGPL-3.0-only

lint:
  source_roots:
    - pkg

repo:
  license:
    spdx_identifier: AGPL-3.0-only
    copyright: 2026 Blackcat Informatics Inc. <paudley@blackcat.ca>
    text: |
      Coding Ethos reference repository license.

      Copyright (c) <year> <copyright holders>
