# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcat.ca>
# SPDX-License-Identifier: AGPL-3.0-only

"""Render normalized ethos bundles into root files and supporting documents.

These renderers own the generated Markdown layout for root agent files, shared
indexes, per-principle detail docs, and prompt addons.
They are the only place where output shape should change by design.
"""

from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from coding_ethos.models import EthosBundle, EthosSkill, Principle

GENERATED_NOTICE = (
    "<!-- Generated by coding-ethos. Edit coding_ethos.yml and repo_ethos.yml, "
    "then regenerate. -->"
)
SPDX_COPYRIGHT = (
    "SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcat.ca>"
)
MARKDOWN_SPDX_LINES = [
    f"<!-- {SPDX_COPYRIGHT} -->",
    "<!-- SPDX-License-Identifier: AGPL-3.0-only -->",
]


@dataclass(frozen=True, slots=True)
class AgentRootSurface:
    """One generated root-file surface for an agent."""

    agent: str
    path: str
    render_root: Callable[[EthosBundle, Path], str]
    render_addendum: Callable[[EthosBundle, Path], str]
    imports: tuple[str, ...] = ()
    merge_topics: tuple[str, ...] = ()


def _join_lines(lines: list[str]) -> str:
    return "\n".join(lines).rstrip() + "\n"


def _with_markdown_spdx(lines: list[str]) -> list[str]:
    return [*MARKDOWN_SPDX_LINES, "", *lines]


def _repo_display_name(bundle: EthosBundle, repo_root: Path) -> str:
    return bundle.repo.name or repo_root.name


def _ethos_title(bundle: EthosBundle) -> str:
    title = bundle.title.strip() or "Engineering Ethos"
    prefix = "ETHOS.md:"
    if title.startswith(prefix):
        return title[len(prefix) :].strip() or "Engineering Ethos"
    return title


def _command_lines(bundle: EthosBundle) -> list[str]:
    lines: list[str] = []
    for label, commands in bundle.repo.commands.items():
        if not commands:
            continue
        command_text = "; ".join(commands)
        lines.append(f"- `{label}`: `{command_text}`")
    return lines


def _path_lines(bundle: EthosBundle) -> list[str]:
    return [f"- `{name}`: `{path}`" for name, path in bundle.repo.paths.items()]


def _format_quick_ref(items: list[str], limit: int = 3) -> str:
    return " | ".join(item.strip() for item in items[:limit])


def _skill_entrypoint(skill: EthosSkill) -> str:
    return f"{skill.id}/SKILL.md"


def _skills_by_id(bundle: EthosBundle, skill_id: str) -> list[EthosSkill]:
    return [skill for skill in bundle.skills if skill.id == skill_id]


def _agent_operating_discipline_lines(
    bundle: EthosBundle,
    *,
    heading: str = "## Agent Operating Discipline",
) -> list[str]:
    matching_skills = _skills_by_id(bundle, "agent-operating-discipline")
    if not matching_skills:
        return []
    skill = matching_skills[0]

    return [
        heading,
        (
            "- Load `.agents/skills/"
            f"{_skill_entrypoint(skill)}` before broad implementation, "
            "refactor, review, or debugging work."
        ),
        (
            "- State task interpretation, assumptions, ambiguity, and "
            "trade-offs before broad changes."
        ),
        (
            "- Prefer the smallest sufficient implementation; avoid "
            "speculative abstractions, options, and extension points."
        ),
        (
            "- Keep edits surgical: every changed line should trace to the "
            "request or cleanup directly caused by the change."
        ),
        (
            "- Define verifiable success criteria and run focused checks "
            "before claiming completion."
        ),
    ]


def _append_repo_context(
    lines: list[str], bundle: EthosBundle, repo_root: Path
) -> None:
    if not (bundle.repo.name or bundle.repo.overview or bundle.repo.notes):
        return
    lines.extend(["## Repo Context"])
    if bundle.repo.name:
        lines.append(f"- Repo: `{_repo_display_name(bundle, repo_root)}`")
    if bundle.repo.overview:
        lines.append(f"- Overview: {bundle.repo.overview}")
    lines.extend(f"- {note}" for note in bundle.repo.notes)
    lines.append("")


def _principle_lines(principles: list[Principle]) -> list[str]:
    lines: list[str] = []
    for principle in principles:
        primary_line = principle.directive or principle.summary
        if principle.tags:
            lines.append(
                f"- `{principle.order:02d}. {principle.title}`: {primary_line} "
                f"[tags: {', '.join(principle.tags)}]"
            )
        else:
            lines.append(
                f"- `{principle.order:02d}. {principle.title}`: {primary_line}"
            )
        if principle.quick_ref:
            lines.append(f"  Quick ref: {_format_quick_ref(principle.quick_ref)}")
    return lines


def render_agents_md(bundle: EthosBundle, repo_root: Path) -> str:
    """Render the repo's generated `AGENTS.md` root file."""
    codex_profile = bundle.agent_profiles.get("codex")
    lines = [
        GENERATED_NOTICE,
        "# AGENTS.md",
        "",
        "## Purpose",
        f"- Repo: `{_repo_display_name(bundle, repo_root)}`",
    ]
    if bundle.repo.overview:
        lines.append(f"- Overview: {bundle.repo.overview}")
    elif bundle.overview:
        lines.append(f"- Shared ethos: {bundle.overview.replace(chr(10), ' ')}")

    command_lines = _command_lines(bundle)
    if command_lines:
        lines.extend(["", "## Commands", *command_lines])

    path_lines = _path_lines(bundle)
    if path_lines:
        lines.extend(["", "## Key Paths", *path_lines])

    if bundle.repo.notes:
        lines.extend(
            ["", "## Repo Notes", *[f"- {note}" for note in bundle.repo.notes]]
        )

    operating_lines = _agent_operating_discipline_lines(bundle)
    if operating_lines:
        lines.extend(["", *operating_lines])

    lines.extend(
        [
            "",
            "## Non-Negotiable Ethos",
            *_principle_lines(bundle.principles),
            "",
            "## Detail Docs",
            (
                "- Deep reference notes live in `.agents/ethos/README.md` "
                "and the linked per-principle docs."
            ),
        ]
    )

    combined_notes: list[str] = []
    if codex_profile:
        combined_notes.extend(codex_profile.notes)
    combined_notes.extend(bundle.repo.agent_notes.get("codex", []))
    if combined_notes:
        lines.extend(["", "## Codex Notes", *[f"- {note}" for note in combined_notes]])

    return _join_lines(_with_markdown_spdx(lines))


def render_agents_addendum(bundle: EthosBundle, repo_root: Path) -> str:
    """Render the managed additive AGENTS block used in inject merges."""
    codex_profile = bundle.agent_profiles.get("codex")
    lines = [
        "## Coding Ethos",
        f"- Managed additive guidance for `{_repo_display_name(bundle, repo_root)}`.",
        (
            "- Keep the hand-written repo guidance above authoritative for "
            "repo-specific operations and edge cases."
        ),
        "- Shared ethos index: `.agents/ethos/README.md`.",
        "- Per-principle detail docs: `.agents/ethos/*.md`.",
        "- Optional prompt addon: `.agent-context/prompt-addons/codex.md`.",
        (
            "- Update `repo_ethos.yml` when repo-specific guidance should "
            "refine shared ethos behavior."
        ),
    ]
    operating_lines = _agent_operating_discipline_lines(
        bundle,
        heading="### Agent Operating Discipline",
    )
    if operating_lines:
        lines.extend(["", *operating_lines])
    lines.extend(["", "### Ethos Priorities", *_principle_lines(bundle.principles)])

    combined_notes: list[str] = []
    if codex_profile:
        combined_notes.extend(codex_profile.notes)
    combined_notes.extend(bundle.repo.agent_notes.get("codex", []))
    if combined_notes:
        lines.extend(["", "### Codex Notes", *[f"- {note}" for note in combined_notes]])

    return _join_lines(_with_markdown_spdx(lines))


def render_shared_ethos_index(bundle: EthosBundle, repo_root: Path) -> str:
    """Render the shared `.agents/ethos/README.md` index."""
    lines = [
        GENERATED_NOTICE,
        f"# {_repo_display_name(bundle, repo_root)} ethos reference",
        "",
        "## Principles",
    ]
    for principle in bundle.principles:
        summary = principle.directive or principle.summary
        lines.append(
            f"- [{principle.order:02d}. {principle.title}]"
            f"({principle.id}.md) - {summary}"
        )
    return _join_lines(_with_markdown_spdx(lines))


def _ethos_repo_context_lines(bundle: EthosBundle, repo_root: Path) -> list[str]:
    if not (bundle.repo.name or bundle.repo.overview or bundle.repo.notes):
        return []

    lines = ["## Repo Context", f"- Repo: `{_repo_display_name(bundle, repo_root)}`"]
    if bundle.repo.overview:
        lines.append(f"- Overview: {bundle.repo.overview}")
    lines.extend(f"- {note}" for note in bundle.repo.notes)
    lines.append("")

    return lines


def _principle_axiom_lines(principle: Principle) -> list[str]:
    if not principle.axioms:
        return []

    lines = ["### Axioms"]
    lines.extend(
        f"- {axiom.axiom}" + (f" {axiom.action}" if axiom.action else "")
        for axiom in principle.axioms
    )
    lines.append("")

    return lines


def _ethos_principle_lines(principle: Principle) -> list[str]:
    lines = [
        "",
        f"## {principle.order:02d}. {principle.title}",
        "",
        principle.summary,
        "",
    ]

    if principle.directive:
        lines.extend(["### Directive", principle.directive, ""])
    if principle.quick_ref:
        lines.extend(
            ["### Quick Ref", *[f"- {item}" for item in principle.quick_ref], ""]
        )

    lines.extend(_principle_axiom_lines(principle))

    if principle.tags:
        lines.extend(["### Tags", f"- {', '.join(principle.tags)}", ""])

    for section in principle.sections:
        lines.extend([f"### {section.title}", section.body, ""])

    return lines


def render_ethos_md(bundle: EthosBundle, repo_root: Path) -> str:
    """Render the full human-readable `ETHOS.md` document."""
    lines = [
        GENERATED_NOTICE,
        f"# {_ethos_title(bundle)}",
        "",
    ]

    if bundle.overview:
        lines.extend([bundle.overview, ""])

    lines.extend(_ethos_repo_context_lines(bundle, repo_root))

    lines.extend(["## Principles"])
    for principle in bundle.principles:
        lines.extend(_ethos_principle_lines(principle))

    return _join_lines(_with_markdown_spdx(lines))


def render_principle_detail(
    bundle: EthosBundle, principle: Principle, repo_root: Path
) -> str:
    """Render one per-principle detail document under `.agents/ethos/`."""
    lines = [
        GENERATED_NOTICE,
        f"# {principle.order:02d}. {principle.title}",
        "",
        "## Summary",
        principle.summary,
        "",
    ]

    if principle.directive:
        lines.extend(["## Directive", principle.directive, ""])

    if principle.quick_ref:
        lines.extend(
            ["## Quick Ref", *[f"- {item}" for item in principle.quick_ref], ""]
        )

    if principle.axioms:
        lines.extend(
            [
                "## Axioms",
                *[
                    f"- {axiom.axiom}" + (f" {axiom.action}" if axiom.action else "")
                    for axiom in principle.axioms
                ],
                "",
            ]
        )

    if principle.merge_topics:
        lines.extend(
            ["## Merge Topics", *[f"- {item}" for item in principle.merge_topics], ""]
        )

    if principle.tags:
        lines.extend(["## Tags", f"- {', '.join(principle.tags)}", ""])

    if principle.related:
        lines.extend(
            [
                "## Related",
                *[f"- [{related}]({related}.md)" for related in principle.related],
                "",
            ]
        )

    if principle.agent_hints:
        lines.extend(
            [
                "## Agent Hints",
                *[
                    f"- `{agent}`: {hint}"
                    for agent, hint in sorted(principle.agent_hints.items())
                ],
                "",
            ]
        )

    _append_repo_context(lines, bundle, repo_root)

    for section in principle.sections:
        lines.extend([f"## {section.title}", section.body, ""])

    return _join_lines(_with_markdown_spdx(lines))


def _render_claude_root(bundle: EthosBundle, repo_root: Path) -> str:
    del repo_root
    return render_claude_md(bundle)


def render_claude_md(bundle: EthosBundle) -> str:
    """Render the generated `CLAUDE.md` import hub."""
    claude_profile = bundle.agent_profiles.get("claude")
    lines = [
        GENERATED_NOTICE,
        "@AGENTS.md",
        "@.claude/ethos/MEMORY.md",
        "",
        "# Claude Code",
        "",
    ]
    if claude_profile:
        lines.extend(f"- {note}" for note in claude_profile.notes)
    else:
        lines.extend(
            [
                (
                    "- Keep the shared contract in `AGENTS.md`; use this file "
                    "only for Claude-specific guidance."
                ),
                (
                    "- The imported memory index mirrors Claude's memory "
                    "style and points at one deep note per ethos entry."
                ),
            ]
        )
    lines.append(
        "- Open the linked ethos note before changing architecture, "
        "validation, error handling, security, or delegation behavior."
    )
    operating_lines = _agent_operating_discipline_lines(bundle)
    if operating_lines:
        lines.extend(["", *operating_lines])
    lines.extend(f"- {note}" for note in bundle.repo.agent_notes.get("claude", []))
    return _join_lines(_with_markdown_spdx(lines))


def render_claude_addendum(bundle: EthosBundle, repo_root: Path) -> str:
    """Render the managed additive Claude block used in inject merges."""
    lines = [
        "## Coding Ethos",
        f"- Managed additive guidance for `{_repo_display_name(bundle, repo_root)}`.",
        (
            "- Keep the existing repo-specific Claude guidance above; this "
            "section is only the generated ethos layer."
        ),
        "- Shared ethos index: `.agents/ethos/README.md`.",
        "- Claude memory index: `.claude/ethos/MEMORY.md`.",
        "- Optional prompt addon: `.agent-context/prompt-addons/claude.md`.",
        (
            "- Open the matching ethos note before changing architecture, "
            "validation, error handling, security, or delegation behavior."
        ),
    ]
    operating_lines = _agent_operating_discipline_lines(
        bundle,
        heading="### Agent Operating Discipline",
    )
    if operating_lines:
        lines.extend(["", *operating_lines])
    repo_notes = bundle.repo.agent_notes.get("claude", [])
    if repo_notes:
        lines.extend(["", "### Claude Notes", *[f"- {note}" for note in repo_notes]])
    lines.extend(
        ["", "### High-Priority Principles", *_principle_lines(bundle.principles[:5])]
    )
    return _join_lines(_with_markdown_spdx(lines))


def render_claude_memory(bundle: EthosBundle, repo_root: Path) -> str:
    """Render the Claude memory index file."""
    lines = [
        GENERATED_NOTICE,
        f"# {_repo_display_name(bundle, repo_root)} ethos memory",
        "",
        "## Shared Ethos",
    ]
    for principle in bundle.principles:
        summary = principle.directive or principle.summary
        lines.append(
            f"- [{principle.title}](../../.agents/ethos/{principle.id}.md) - {summary}"
        )
    return _join_lines(_with_markdown_spdx(lines))


def render_gemini_md(bundle: EthosBundle, repo_root: Path) -> str:
    """Render the generated `GEMINI.md` root guidance file."""
    gemini_profile = bundle.agent_profiles.get("gemini")
    lines = [
        GENERATED_NOTICE,
        "@AGENTS.md",
        "",
        f"# GEMINI.md for {_repo_display_name(bundle, repo_root)}",
        "",
    ]
    if gemini_profile:
        lines.extend(f"- {note}" for note in gemini_profile.notes)
    else:
        lines.extend(
            [
                "- `AGENTS.md` is the durable project contract for this repository.",
                (
                    "- Prefer targeted reads of `.agents/ethos/README.md` "
                    "and individual detail docs instead of inlining the full "
                    "corpus."
                ),
            ]
        )
    lines.append(
        "- Keep repo-specific conventions in `repo_ethos.yml`; regenerate "
        "after updating it."
    )
    operating_lines = _agent_operating_discipline_lines(bundle)
    if operating_lines:
        lines.extend(["", *operating_lines])
    lines.extend(f"- {note}" for note in bundle.repo.agent_notes.get("gemini", []))
    return _join_lines(_with_markdown_spdx(lines))


def render_gemini_addendum(bundle: EthosBundle, repo_root: Path) -> str:
    """Render the managed additive Gemini block used in inject merges."""
    lines = [
        "## Coding Ethos",
        f"- Managed additive guidance for `{_repo_display_name(bundle, repo_root)}`.",
        (
            "- Keep the hand-written repo guidance above; use this generated "
            "section as the shared ethos layer."
        ),
        "- Durable repo contract: `AGENTS.md`.",
        "- Shared ethos index: `.agents/ethos/README.md`.",
        "- Optional prompt addon: `.agent-context/prompt-addons/gemini.md`.",
    ]
    operating_lines = _agent_operating_discipline_lines(
        bundle,
        heading="### Agent Operating Discipline",
    )
    if operating_lines:
        lines.extend(["", *operating_lines])
    repo_notes = bundle.repo.agent_notes.get("gemini", [])
    if repo_notes:
        lines.extend(["", "### Gemini Notes", *[f"- {note}" for note in repo_notes]])
    lines.extend(
        ["", "### High-Priority Principles", *_principle_lines(bundle.principles[:5])]
    )
    return _join_lines(_with_markdown_spdx(lines))


def required_root_imports(target_name: str) -> list[str]:
    """Return required import lines for a generated root file."""
    for surface in _AGENT_ROOT_SURFACES:
        if surface.path == target_name:
            return list(surface.imports)
    return []


def render_prompt_addon(bundle: EthosBundle, agent: str, repo_root: Path) -> str:
    """Render the small fallback prompt addon for one supported agent."""
    top_principles = bundle.principles[:5]
    lines = [
        f"# {agent.title()} prompt addon",
        "",
        f"You are working in `{_repo_display_name(bundle, repo_root)}`.",
        "Treat `AGENTS.md` as the source of truth when it is present.",
        (
            "If a task touches architecture, validation, error handling, or "
            "delegation, consult the matching detail doc under "
            "`.agents/ethos/` before acting."
        ),
        "",
        "Core principles:",
    ]
    lines.extend(
        f"- {principle.title}: {principle.directive or principle.summary}"
        for principle in top_principles
    )
    lines.extend(
        (
            f"- {principle.title} quick ref: "
            f"{_format_quick_ref(principle.quick_ref, limit=2)}"
        )
        for principle in top_principles
        if principle.quick_ref
    )
    return _join_lines(_with_markdown_spdx(lines))


_AGENT_ROOT_SURFACES: tuple[AgentRootSurface, ...] = (
    AgentRootSurface(
        agent="codex",
        path="AGENTS.md",
        render_root=render_agents_md,
        render_addendum=render_agents_addendum,
        merge_topics=("repo commands", "key paths", "repo operating notes"),
    ),
    AgentRootSurface(
        agent="claude",
        path="CLAUDE.md",
        render_root=_render_claude_root,
        render_addendum=render_claude_addendum,
        imports=("@AGENTS.md", "@.claude/ethos/MEMORY.md"),
        merge_topics=(
            "Claude imports",
            "memory links",
            "Claude-specific workflow notes",
        ),
    ),
    AgentRootSurface(
        agent="gemini",
        path="GEMINI.md",
        render_root=render_gemini_md,
        render_addendum=render_gemini_addendum,
        imports=("@AGENTS.md",),
        merge_topics=(
            "Gemini root guidance",
            "linked detail docs",
            "repo operating notes",
        ),
    ),
)


def agent_root_surfaces() -> tuple[AgentRootSurface, ...]:
    """Return registered generated root-file surfaces for supported agents."""
    return _AGENT_ROOT_SURFACES


def render_agent_root_outputs(bundle: EthosBundle, repo_root: Path) -> dict[str, str]:
    """Render registered root files for all supported agent surfaces."""
    return {
        surface.path: surface.render_root(bundle, repo_root)
        for surface in _AGENT_ROOT_SURFACES
    }


def render_agent_addendum(
    bundle: EthosBundle, repo_root: Path, target_name: str, fallback: str
) -> str:
    """Render the managed addendum for a registered root file."""
    for surface in _AGENT_ROOT_SURFACES:
        if surface.path == target_name:
            return surface.render_addendum(bundle, repo_root)
    return fallback


def root_merge_topics(target_name: str) -> list[str]:
    """Return root-file-specific merge topics for registered agent surfaces."""
    for surface in _AGENT_ROOT_SURFACES:
        if surface.path == target_name:
            return list(surface.merge_topics)
    return []
