# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcat.ca>
# SPDX-License-Identifier: AGPL-3.0-only

"""Shared Markdown rendering helpers for generated ethos files.

Responsibility is narrow.
Public imports stay aligned.
"""

from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from coding_ethos.models import EthosBundle
from coding_ethos.renderer_principles import (
    agent_operating_discipline_lines,
    append_repo_context,
    format_quick_ref,
    principle_lines,
)

__all__ = [
    "GENERATED_NOTICE",
    "AgentRootSurface",
    "agent_operating_discipline_lines",
    "append_repo_context",
    "command_lines",
    "ethos_title",
    "format_quick_ref",
    "join_lines",
    "path_lines",
    "principle_lines",
    "repo_display_name",
    "with_markdown_spdx",
]

GENERATED_NOTICE = (
    "<!-- Generated by coding-ethos. Edit coding_ethos.yml and repo_ethos.yml, "
    "then regenerate. -->"
)
SPDX_COPYRIGHT = (
    "SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcat.ca>"
)
MARKDOWN_SPDX_LINES = [
    f"<!-- {SPDX_COPYRIGHT} -->",
    "<!-- SPDX-License-Identifier: AGPL-3.0-only -->",
]


@dataclass(frozen=True, slots=True)
class AgentRootSurface:
    """One generated root-file surface for an agent."""

    agent: str
    path: str
    render_root: Callable[[EthosBundle, Path], str]
    render_addendum: Callable[[EthosBundle, Path], str]
    imports: tuple[str, ...] = ()
    merge_topics: tuple[str, ...] = ()


def join_lines(lines: list[str]) -> str:
    """Provide focused helper behavior for the split module."""
    return "\n".join(lines).rstrip() + "\n"


def with_markdown_spdx(lines: list[str]) -> list[str]:
    """Provide focused helper behavior for the split module."""
    return [*MARKDOWN_SPDX_LINES, "", *lines]


def repo_display_name(bundle: EthosBundle, repo_root: Path) -> str:
    """Provide focused helper behavior for the split module."""
    return bundle.repo.name or repo_root.name


def ethos_title(bundle: EthosBundle) -> str:
    """Provide focused helper behavior for the split module."""
    title = bundle.title.strip() or "Engineering Ethos"
    prefix = "ETHOS.md:"
    if title.startswith(prefix):
        return title[len(prefix) :].strip() or "Engineering Ethos"
    return title


def command_lines(bundle: EthosBundle) -> list[str]:
    """Provide focused helper behavior for the split module."""
    lines: list[str] = []
    for label, commands in bundle.repo.commands.items():
        if not commands:
            continue
        command_text = "; ".join(commands)
        lines.append(f"- `{label}`: `{command_text}`")
    return lines


def path_lines(bundle: EthosBundle) -> list[str]:
    """Provide focused helper behavior for the split module."""
    return [f"- `{name}`: `{path}`" for name, path in bundle.repo.paths.items()]
