# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcat.ca>
# SPDX-License-Identifier: MIT

from __future__ import annotations

from pathlib import Path

from coding_ethos.models import EthosBundle, Principle

GENERATED_NOTICE = (
    "<!-- Generated by coding-ethos. Edit coding_ethos.yml and repo_ethos.yml, "
    "then regenerate. -->"
)


def _join_lines(lines: list[str]) -> str:
    return "\n".join(lines).rstrip() + "\n"


def _repo_display_name(bundle: EthosBundle, repo_root: Path) -> str:
    return bundle.repo.name or repo_root.name


def _ethos_title(bundle: EthosBundle) -> str:
    title = bundle.title.strip() or "Engineering Ethos"
    prefix = "ETHOS.md:"
    if title.startswith(prefix):
        return title[len(prefix) :].strip() or "Engineering Ethos"
    return title


def _command_lines(bundle: EthosBundle) -> list[str]:
    lines: list[str] = []
    for label, commands in bundle.repo.commands.items():
        if not commands:
            continue
        command_text = "; ".join(commands)
        lines.append(f"- `{label}`: `{command_text}`")
    return lines


def _path_lines(bundle: EthosBundle) -> list[str]:
    return [f"- `{name}`: `{path}`" for name, path in bundle.repo.paths.items()]


def _format_quick_ref(items: list[str], limit: int = 3) -> str:
    return " | ".join(item.strip() for item in items[:limit])


def _principle_lines(principles: list[Principle]) -> list[str]:
    lines: list[str] = []
    for principle in principles:
        primary_line = principle.directive or principle.summary
        if principle.tags:
            lines.append(
                f"- `{principle.order:02d}. {principle.title}`: {primary_line} "
                f"[tags: {', '.join(principle.tags)}]"
            )
        else:
            lines.append(f"- `{principle.order:02d}. {principle.title}`: {primary_line}")
        if principle.quick_ref:
            lines.append(f"  Quick ref: {_format_quick_ref(principle.quick_ref)}")
    return lines


def render_agents_md(bundle: EthosBundle, repo_root: Path) -> str:
    codex_profile = bundle.agent_profiles.get("codex")
    lines = [
        GENERATED_NOTICE,
        "# AGENTS.md",
        "",
        "## Purpose",
        f"- Repo: `{_repo_display_name(bundle, repo_root)}`",
    ]
    if bundle.repo.overview:
        lines.append(f"- Overview: {bundle.repo.overview}")
    elif bundle.overview:
        lines.append(f"- Shared ethos: {bundle.overview.replace(chr(10), ' ')}")

    command_lines = _command_lines(bundle)
    if command_lines:
        lines.extend(["", "## Commands", *command_lines])

    path_lines = _path_lines(bundle)
    if path_lines:
        lines.extend(["", "## Key Paths", *path_lines])

    if bundle.repo.notes:
        lines.extend(["", "## Repo Notes", *[f"- {note}" for note in bundle.repo.notes]])

    lines.extend(
        [
            "",
            "## Non-Negotiable Ethos",
            *_principle_lines(bundle.principles),
            "",
            "## Detail Docs",
            "- Deep reference notes live in `.agents/ethos/README.md` and the linked per-principle docs.",
        ]
    )

    combined_notes = []
    if codex_profile:
        combined_notes.extend(codex_profile.notes)
    combined_notes.extend(bundle.repo.agent_notes.get("codex", []))
    if combined_notes:
        lines.extend(["", "## Codex Notes", *[f"- {note}" for note in combined_notes]])

    return _join_lines(lines)


def render_agents_addendum(bundle: EthosBundle, repo_root: Path) -> str:
    codex_profile = bundle.agent_profiles.get("codex")
    lines = [
        "## Coding Ethos",
        f"- Managed additive guidance for `{_repo_display_name(bundle, repo_root)}`.",
        "- Keep the hand-written repo guidance above authoritative for repo-specific operations and edge cases.",
        "- Shared ethos index: `.agents/ethos/README.md`.",
        "- Per-principle detail docs: `.agents/ethos/*.md`.",
        "- Optional prompt addon: `.agent-context/prompt-addons/codex.md`.",
        "- Update `repo_ethos.yml` when repo-specific guidance should refine shared ethos behavior.",
        "",
        "### Ethos Priorities",
        *_principle_lines(bundle.principles),
    ]

    combined_notes: list[str] = []
    if codex_profile:
        combined_notes.extend(codex_profile.notes)
    combined_notes.extend(bundle.repo.agent_notes.get("codex", []))
    if combined_notes:
        lines.extend(["", "### Codex Notes", *[f"- {note}" for note in combined_notes]])

    return _join_lines(lines)


def render_shared_ethos_index(bundle: EthosBundle, repo_root: Path) -> str:
    lines = [
        GENERATED_NOTICE,
        f"# {_repo_display_name(bundle, repo_root)} ethos reference",
        "",
        "## Principles",
    ]
    for principle in bundle.principles:
        summary = principle.directive or principle.summary
        lines.append(f"- [{principle.order:02d}. {principle.title}]({principle.id}.md) - {summary}")
    return _join_lines(lines)


def render_ethos_md(bundle: EthosBundle, repo_root: Path) -> str:
    lines = [
        GENERATED_NOTICE,
        f"# {_ethos_title(bundle)}",
        "",
    ]

    if bundle.overview:
        lines.extend([bundle.overview, ""])

    if bundle.repo.name or bundle.repo.overview or bundle.repo.notes:
        lines.extend(["## Repo Context"])
        lines.append(f"- Repo: `{_repo_display_name(bundle, repo_root)}`")
        if bundle.repo.overview:
            lines.append(f"- Overview: {bundle.repo.overview}")
        lines.extend(f"- {note}" for note in bundle.repo.notes)
        lines.append("")

    lines.extend(["## Principles"])
    for principle in bundle.principles:
        lines.extend(
            [
                "",
                f"## {principle.order:02d}. {principle.title}",
                "",
                principle.summary,
                "",
            ]
        )

        if principle.directive:
            lines.extend(["### Directive", principle.directive, ""])

        if principle.quick_ref:
            lines.extend(["### Quick Ref", *[f"- {item}" for item in principle.quick_ref], ""])

        if principle.tags:
            lines.extend(["### Tags", f"- {', '.join(principle.tags)}", ""])

        for section in principle.sections:
            lines.extend([f"### {section.title}", section.body, ""])

    return _join_lines(lines)


def render_principle_detail(bundle: EthosBundle, principle: Principle, repo_root: Path) -> str:
    lines = [
        GENERATED_NOTICE,
        f"# {principle.order:02d}. {principle.title}",
        "",
        "## Summary",
        principle.summary,
        "",
    ]

    if principle.directive:
        lines.extend(["## Directive", principle.directive, ""])

    if principle.quick_ref:
        lines.extend(["## Quick Ref", *[f"- {item}" for item in principle.quick_ref], ""])

    if principle.merge_topics:
        lines.extend(["## Merge Topics", *[f"- {item}" for item in principle.merge_topics], ""])

    if principle.tags:
        lines.extend(["## Tags", f"- {', '.join(principle.tags)}", ""])

    if principle.related:
        lines.extend(["## Related", *[f"- [{related}]({related}.md)" for related in principle.related], ""])

    if principle.agent_hints:
        lines.extend(
            ["## Agent Hints", *[f"- `{agent}`: {hint}" for agent, hint in sorted(principle.agent_hints.items())], ""]
        )

    if bundle.repo.name or bundle.repo.overview or bundle.repo.notes:
        lines.extend(["## Repo Context"])
        if bundle.repo.name:
            lines.append(f"- Repo: `{_repo_display_name(bundle, repo_root)}`")
        if bundle.repo.overview:
            lines.append(f"- Overview: {bundle.repo.overview}")
        lines.extend(f"- {note}" for note in bundle.repo.notes)
        lines.append("")

    for section in principle.sections:
        lines.extend([f"## {section.title}", section.body, ""])

    return _join_lines(lines)


def render_claude_md(bundle: EthosBundle) -> str:
    claude_profile = bundle.agent_profiles.get("claude")
    lines = [
        GENERATED_NOTICE,
        "@AGENTS.md",
        "@.claude/ethos/MEMORY.md",
        "",
        "# Claude Code",
        "",
    ]
    if claude_profile:
        lines.extend(f"- {note}" for note in claude_profile.notes)
    else:
        lines.extend(
            [
                "- Keep the shared contract in `AGENTS.md`; use this file only for Claude-specific guidance.",
                "- The imported memory index mirrors Claude's memory style and points at one deep note per ethos entry.",
            ]
        )
    lines.append(
        "- Open the linked ethos note before changing architecture, validation, error handling, security, or delegation behavior."
    )
    lines.extend(f"- {note}" for note in bundle.repo.agent_notes.get("claude", []))
    return _join_lines(lines)


def render_claude_addendum(bundle: EthosBundle, repo_root: Path) -> str:
    lines = [
        "## Coding Ethos",
        f"- Managed additive guidance for `{_repo_display_name(bundle, repo_root)}`.",
        "- Keep the existing repo-specific Claude guidance above; this section is only the generated ethos layer.",
        "- Shared ethos index: `.agents/ethos/README.md`.",
        "- Claude memory index: `.claude/ethos/MEMORY.md`.",
        "- Optional prompt addon: `.agent-context/prompt-addons/claude.md`.",
        "- Open the matching ethos note before changing architecture, validation, error handling, security, or delegation behavior.",
    ]
    repo_notes = bundle.repo.agent_notes.get("claude", [])
    if repo_notes:
        lines.extend(["", "### Claude Notes", *[f"- {note}" for note in repo_notes]])
    lines.extend(["", "### High-Priority Principles", *_principle_lines(bundle.principles[:5])])
    return _join_lines(lines)


def render_claude_memory(bundle: EthosBundle, repo_root: Path) -> str:
    lines = [
        GENERATED_NOTICE,
        f"# {_repo_display_name(bundle, repo_root)} ethos memory",
        "",
        "## Shared Ethos",
    ]
    for principle in bundle.principles:
        summary = principle.directive or principle.summary
        lines.append(f"- [{principle.title}](../../.agents/ethos/{principle.id}.md) - {summary}")
    return _join_lines(lines)


def render_gemini_md(bundle: EthosBundle, repo_root: Path) -> str:
    gemini_profile = bundle.agent_profiles.get("gemini")
    lines = [
        GENERATED_NOTICE,
        "@AGENTS.md",
        "",
        f"# GEMINI.md for {_repo_display_name(bundle, repo_root)}",
        "",
    ]
    if gemini_profile:
        lines.extend(f"- {note}" for note in gemini_profile.notes)
    else:
        lines.extend(
            [
                "- `AGENTS.md` is the durable project contract for this repository.",
                "- Prefer targeted reads of `.agents/ethos/README.md` and individual detail docs instead of inlining the full corpus.",
            ]
        )
    lines.append("- Keep repo-specific conventions in `repo_ethos.yml`; regenerate after updating it.")
    lines.extend(f"- {note}" for note in bundle.repo.agent_notes.get("gemini", []))
    return _join_lines(lines)


def render_gemini_addendum(bundle: EthosBundle, repo_root: Path) -> str:
    lines = [
        "## Coding Ethos",
        f"- Managed additive guidance for `{_repo_display_name(bundle, repo_root)}`.",
        "- Keep the hand-written repo guidance above; use this generated section as the shared ethos layer.",
        "- Durable repo contract: `AGENTS.md`.",
        "- Shared ethos index: `.agents/ethos/README.md`.",
        "- Optional prompt addon: `.agent-context/prompt-addons/gemini.md`.",
    ]
    repo_notes = bundle.repo.agent_notes.get("gemini", [])
    if repo_notes:
        lines.extend(["", "### Gemini Notes", *[f"- {note}" for note in repo_notes]])
    lines.extend(["", "### High-Priority Principles", *_principle_lines(bundle.principles[:5])])
    return _join_lines(lines)


def required_root_imports(target_name: str) -> list[str]:
    if target_name == "CLAUDE.md":
        return ["@AGENTS.md", "@.claude/ethos/MEMORY.md"]
    if target_name == "GEMINI.md":
        return ["@AGENTS.md"]
    return []


def render_prompt_addon(bundle: EthosBundle, agent: str, repo_root: Path) -> str:
    top_principles = bundle.principles[:5]
    lines = [
        f"# {agent.title()} prompt addon",
        "",
        f"You are working in `{_repo_display_name(bundle, repo_root)}`.",
        "Treat `AGENTS.md` as the source of truth when it is present.",
        "If a task touches architecture, validation, error handling, or delegation, consult the matching detail doc under `.agents/ethos/` before acting.",
        "",
        "Core principles:",
    ]
    lines.extend(
        f"- {principle.title}: {principle.directive or principle.summary}" for principle in top_principles
    )
    for principle in top_principles:
        if principle.quick_ref:
            lines.append(f"- {principle.title} quick ref: {_format_quick_ref(principle.quick_ref, limit=2)}")
    return _join_lines(lines)
